### ISSUE TITLE
crashes with `jshell` 

### ISSUE THREAD

**Issue by goyalyashpal** [adoptium/adoptium-support#1011]
### Please provide a brief summary of the bug

`jshell` is crashing again and again for one reason or the other

### duplicate search

* [jshell](https://github.com/adoptium/adoptium-support/issues?q=is%3Aissue+jshell+is%3Aclosed): 2 existing matches, but not related
* [Exception during analyze](https://github.com/adoptium/adoptium-support/issues?q=is%3Aissue+Exception+during+analyze): 0 existing matches
* [tree.starImportScope ](https://github.com/adoptium/adoptium-support/issues?q=is%3Aissue+tree.starImportScope)
* [JavacTaskImpl.java](https://github.com/adoptium/adoptium-support/issues?q=is%3Aissue+JavacTaskImpl.java) - https://github.com/adoptium/adoptium-support/issues/678 seems similar, but not same

i came here via [adoptium faq](https://adoptium.net/docs/faq/#_where_do_i_report_a_bug_or_problem_with_eclipse_temurin) while trying to investigate  this issue via jshell https://github.com/allen-ball/ganymede/issues/2

### Did you test with the latest update version?

```Shell
i will test with that post filling here
```

### Please provide steps to reproduce where possible

```shell
$ jshell
```

```shell
$ jshell --help     # this works

$ jshell --no-startup
|  Welcome to JShell -- Version 21.0.1
|  For an introduction type: /help intro

jshell> import java.io.IOException
```

### Expected Results

no crashes

### Actual Results

crashes

### What Java Version are you using?

openjdk 21.0.1 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

### What is your operating system and platform?

windows 10 22h2 on x86-64

### How did you install Java?

OpenJDK21U-jdk_x64_windows_hotspot_21.0.1_12.msi

### Did it work before?

```Shell
this is my first version of using adoptium
```

### Did you test with other Java versions?

```Shell
yes, it worked with Oracle OpenJDK v#20.0.2

jdk-20_windows-x64_bin.msi
```

### Relevant log output

Different parts:

```Shell
$ jshell
<cp1>
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.startUpRun(JShellTool.java:1183)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.resetState(JShellTool.java:1130)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.start(JShellTool.java:955)
<cp2>
        ... 20 more
<cp3>
        ... 21 more

$ jshell --no-startup
|  Welcome to JShell -- Version 21.0.1
|  For an introduction type: /help intro

jshell> import java.io.IOException
<cp1>
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.start(JShellTool.java:1005)
<cp2>
        ... 18 more
<cp3>
        ... 19 more

```

Common parts for both:

1. cp1

```log
Exception in thread "main" java.lang.InternalError: Exception during analyze - java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Scope$
StarImportScope.isFilled()" because "tree.starImportScope" is null
        at jdk.jshell/jdk.jshell.TaskFactory$AnalyzeTask.analyze(TaskFactory.java:415)
        at jdk.jshell/jdk.jshell.TaskFactory$AnalyzeTask.<init>(TaskFactory.java:406)
        at jdk.jshell/jdk.jshell.TaskFactory.lambda$analyze$1(TaskFactory.java:178)
        at jdk.jshell/jdk.jshell.TaskFactory.lambda$runTask$4(TaskFactory.java:213)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskPool.getTask(JavacTaskPool.java:193)
        at jdk.jshell/jdk.jshell.TaskFactory.runTask(TaskFactory.java:206)
        at jdk.jshell/jdk.jshell.TaskFactory.analyze(TaskFactory.java:175)
        at jdk.jshell/jdk.jshell.TaskFactory.analyze(TaskFactory.java:161)
        at jdk.jshell/jdk.jshell.Eval.compileAndLoad(Eval.java:1068)
        at jdk.jshell/jdk.jshell.Eval.declare(Eval.java:901)
        at jdk.jshell/jdk.jshell.Eval.eval(Eval.java:140)
        at jdk.jshell/jdk.jshell.JShell.eval(JShell.java:513)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.processSource(JShellTool.java:3633)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.processSourceCatchingReset(JShellTool.java:1353)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.processInput(JShellTool.java:1251)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.run(JShellTool.java:1222)
Exception in thread "main" java.lang.InternalError: Exception during analyze - java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Scope$
StarImportScope.isFilled()" because "tree.starImportScope" is null
        at jdk.jshell/jdk.jshell.TaskFactory$AnalyzeTask.analyze(TaskFactory.java:415)
        at jdk.jshell/jdk.jshell.TaskFactory$AnalyzeTask.<init>(TaskFactory.java:406)
        at jdk.jshell/jdk.jshell.TaskFactory.lambda$analyze$1(TaskFactory.java:178)
        at jdk.jshell/jdk.jshell.TaskFactory.lambda$runTask$4(TaskFactory.java:213)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskPool.getTask(JavacTaskPool.java:193)
        at jdk.jshell/jdk.jshell.TaskFactory.runTask(TaskFactory.java:206)
        at jdk.jshell/jdk.jshell.TaskFactory.analyze(TaskFactory.java:175)
        at jdk.jshell/jdk.jshell.TaskFactory.analyze(TaskFactory.java:161)
        at jdk.jshell/jdk.jshell.Eval.compileAndLoad(Eval.java:1068)
        at jdk.jshell/jdk.jshell.Eval.declare(Eval.java:901)
        at jdk.jshell/jdk.jshell.Eval.eval(Eval.java:140)
        at jdk.jshell/jdk.jshell.JShell.eval(JShell.java:513)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.processSource(JShellTool.java:3633)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.processSourceCatchingReset(JShellTool.java:1353)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.processInput(JShellTool.java:1251)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.run(JShellTool.java:1222)
```

2. cp2:

```log
        at jdk.jshell/jdk.internal.jshell.tool.JShellToolBuilder.start(JShellToolBuilder.java:261)
        at jdk.jshell/jdk.internal.jshell.tool.JShellToolProvider.main(JShellToolProvider.java:120)
Caused by: java.lang.IllegalStateException: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Scope$StarImportScope.isFilled()" because
 "tree.starImportScope" is null
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:383)
        at jdk.jshell/jdk.jshell.TaskFactory$AnalyzeTask.analyze(TaskFactory.java:412)
```

3. cp3:

```
Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Scope$StarImportScope.isFilled()" because "tree.starImportScope" is null  
        at jdk.compiler/com.sun.tools.javac.comp.TypeEnter.ensureImportsChecked(TypeEnter.java:169)
        at jdk.compiler/com.sun.tools.javac.comp.Enter.complete(Enter.java:632)
        at jdk.compiler/com.sun.tools.javac.comp.Enter.main(Enter.java:592)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1072)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:345)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:399)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$analyze$1(JavacTaskImpl.java:379)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:379)
```

**Comment by karianna** [comment]
@goyalyashpal See if https://stackoverflow.com/questions/75170692/why-jshell-throw-exception-at-startup-at-windows-when-run-jshell-at-my-home-di helps

**Comment by goyalyashpal** [comment]
hi @karianna - yes, the logs seem exactly same. but i was not running at home dir.

and it seems there were just "try this hack" like speculations there in comments - like that `Main.jsh`, not any proper diagnosis.

so, do u have any further suggestions to that  ?
