### ISSUE TITLE
OpenLCA crashes while calculating result

### ISSUE THREAD

**Issue by ayancevs** [adoptium/adoptium-support#1012]
### Please provide a brief summary of the bug

OpenLCA works fine till creating processes, but it crashes while calculating result. 
[hs_err_pid9608.log](https://github.com/adoptium/adoptium-support/files/14090195/hs_err_pid9608.log)

### Expected Results

I want it to run properly

### Actual Results

Aparently not running

### What Java Version are you using?

OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)

**Comment by karianna** [comment]
@ayancevs Please try with 17.0.10 and report back here if it's still a crash

**Comment by ayancevs** [comment]
Hi Karianna. I updated jdk to 21 and now it doesnt crash. But there is another issue. 

Any single process it is able to calculate. But for a system process it is showing error as calculation failed. 

Here is the details from the log:

02:46:48	ERROR	org.openlca.app.util.ErrorReporter	Calculation failed
java.lang.reflect.InvocationTargetException: null
    at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:395)
    at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1034)
    at org.openlca.app.wizards.calculation.CalculationWizard.performFinish(CalculationWizard.java:106)
    at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:833)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:473)
    at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
    at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
    at org.eclipse.jface.window.Window.open(Window.java:799)
    at org.openlca.app.wizards.calculation.CalculationWizard.open(CalculationWizard.java:61)
    at org.openlca.app.editors.systems.CalculationDispatch.call(CalculationDispatch.java:44)
    at org.openlca.app.editors.systems.CalculationDispatch.call(CalculationDispatch.java:25)
    at org.openlca.app.editors.systems.ProductSystemInfoPage.lambda$7(ProductSystemInfoPage.java:110)
    at org.openlca.app.util.Controls$2.widgetSelected(Controls.java:111)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
    at org.openlca.app.rcp.RcpApplication.start(RcpApplication.java:13)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467) java.lang.NullPointerException: null
    at java.base/java.util.Objects.requireNonNull(Unknown Source)
    at org.openlca.core.matrix.index.TechIndex.of(TechIndex.java:100)
    at org.openlca.core.math.SystemCalculator.solve(SystemCalculator.java:70)
    at org.openlca.core.math.SystemCalculator.calculateLazy(SystemCalculator.java:61)
    at org.openlca.app.wizards.calculation.CalculationWizard.runCalculation(CalculationWizard.java:141)
    at org.openlca.app.wizards.calculation.CalculationWizard.lambda$1(CalculationWizard.java:109)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)



What to do now. Can you hekp me?

**Comment by karianna** [comment]
@ayancevs You'll need to ask the OpenLCA folks to see if they support Java 21 (they use native components and reflection so it's not always an automatic guarantee).
