### ISSUE TITLE
Dockerized Image crasshed

### ISSUE THREAD

**Issue by kolchurinvv** [adoptium/adoptium-support#1030]
### Please provide a brief summary of the bug

after a couple of days of regular use on in a docker container hosted on a vps it crashed with Error: java.lang.IllegalStateException

### Did you test with the latest update version?

```Shell
No. I assume that the docker image should have be up-to-date as it is the maintainer's responsibility. just restarting the image didn't work, however downloading a fresh image and then running it actually helped.
```

### Please provide steps to reproduce where possible

```
docker pull plantuml/plantuml-server:jetty
docker run --name diagrams -d -p 4000:8000 plantuml/plantuml-server:jetty
```
then wait about 3-4 days

### Expected Results

container and image stays up and running

### Actual Results

docker container exited with code 134

### What Java Version are you using?

n/a

### What is your operating system and platform?

system:
➜ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Cloud Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Cloud Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
SUPPORT_END=2023-05-16
VARIANT="Cloud Edition"
VARIANT_ID=cloud
➜ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  1
  On-line CPU(s) list:   0
Vendor ID:               GenuineIntel
  Model name:            Intel Core Processor (Haswell, no TSX)
    CPU family:          6
    Model:               60
    Thread(s) per core:  1
    Core(s) per socket:  1
    Socket(s):           1
    Stepping:            1
    BogoMIPS:            4788.90
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse
                         sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmu
                         lqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave a
                         vx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti tpr_shadow vnmi flexprio
                         rity ept vpid ept_ad fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear
Virtualization features:
  Virtualization:        VT-x
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   32 KiB (1 instance)
  L1i:                   32 KiB (1 instance)
  L2:                    4 MiB (1 instance)
  L3:                    16 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0
Vulnerabilities:
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
  Mds:                   Mitigation; Clear CPU buffers; SMT Host state unknown
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Unknown: No mitigations
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Unknown: Dependent on hypervisor status
  Tsx async abort:       Not affected

liminor in /etc/nginx/conf.d  at ovh-s0
➜ free -h
               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       412Mi       158Mi       5.0Mi       1.3Gi       1.3Gi
Swap:          1.9Gi       179Mi       1.7Gi

### How did you install Java?

docker image

### Did it work before?

```Shell
for about 4 days
```

### Did you test with other Java versions?

```Shell
no
```

### Relevant log output

```Shell
➜ sudo docker logs 5321bbaf68990b4e9d4f4525aaebdf6c255176656777937266639f8ca752c13e
2024-02-21 15:41:17.000:INFO:docker-entrypoint:jetty start from /var/lib/jetty/jetty.start
2024-02-21 15:41:20.178:INFO :oejs.Server:main: jetty-11.0.18; built: 2023-10-27T02:14:36.036Z; git: 5a9a771a9fbcb9d36993630850f612581b78c13f; jvm 17.0.9+9
2024-02-21 15:41:20.422:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/]
2024-02-21 15:41:25.809:INFO :oejss.DefaultSessionIdManager:main: Session workerName=node0
2024-02-21 15:41:25.989:INFO :oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@7530ad9c{PlantUML,/,[file:///tmp/jetty-0_0_0_0-8080-plantuml_war-_-any-671331059427054106/webapp/, jar:file:///tmp/jetty-0_0_0_0-8080-plantuml_war-_-any-671331059427054106/webapp/WEB-INF/lib/monaco-editor-0.36.1.jar!/META-INF/resources],AVAILABLE}{/plantuml.war}
2024-02-21 15:41:26.029:INFO :oejs.AbstractConnector:main: Started ServerConnector@11ea5ed1{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2024-02-21 15:41:26.068:INFO :oejs.Server:main: Started Server@61df66b6{STARTING}[11.0.18,sto=5000] @8885ms
Feb 21, 2024 7:30:00 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
java.lang.IllegalStateException // happens multiple times
...
Error java.lang.IllegalStateException
java.lang.IllegalStateException
	at net.atmp.CucaDiagram.getCurrentGroup(CucaDiagram.java:134)
	at net.atmp.CucaDiagram.quarkInContext(CucaDiagram.java:203)
	at net.sourceforge.plantuml.objectdiagram.command.CommandCreateEntityObjectMultilines.executeArg0(CommandCreateEntityObjectMultilines.java:110)
	at net.sourceforge.plantuml.objectdiagram.command.CommandCreateEntityObjectMultilines.executeNow(CommandCreateEntityObjectMultilines.java:93)
	at net.sourceforge.plantuml.objectdiagram.command.CommandCreateEntityObjectMultilines.executeNow(CommandCreateEntityObjectMultilines.java:63)
	at net.sourceforge.plantuml.command.CommandMultilines2.execute(CommandMultilines2.java:112)
	at net.sourceforge.plantuml.command.ProtectedCommand.execute(ProtectedCommand.java:57)
	at net.sourceforge.plantuml.AbstractPSystem.executeCommand(AbstractPSystem.java:186)
	at net.sourceforge.plantuml.command.PSystemCommandFactory.executeFewLines(PSystemCommandFactory.java:125)
	at net.sourceforge.plantuml.command.PSystemCommandFactory.createSystem(PSystemCommandFactory.java:108)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:160)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:188)
	at net.sourceforge.plantuml.servlet.DiagramResponse.getOutputBlockSelection(DiagramResponse.java:218)
	at net.sourceforge.plantuml.servlet.DiagramResponse.sendDiagram(DiagramResponse.java:186)
	at net.sourceforge.plantuml.servlet.UmlDiagramService.doDiagramResponse(UmlDiagramService.java:100)
	at net.sourceforge.plantuml.servlet.UmlDiagramService.doGet(UmlDiagramService.java:62)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
You should send a mail to plantuml@gmail.com or post to https://plantuml.com/qa with this log (V1.2024.3)
Error java.lang.IllegalStateException
java.lang.IllegalStateException
	at net.atmp.CucaDiagram.getCurrentGroup(CucaDiagram.java:134)
	at net.atmp.CucaDiagram.quarkInContext(CucaDiagram.java:203)
	at net.sourceforge.plantuml.objectdiagram.command.CommandCreateEntityObjectMultilines.executeArg0(CommandCreateEntityObjectMultilines.java:110)
	at net.sourceforge.plantuml.objectdiagram.command.CommandCreateEntityObjectMultilines.executeNow(CommandCreateEntityObjectMultilines.java:93)
	at net.sourceforge.plantuml.objectdiagram.command.CommandCreateEntityObjectMultilines.executeNow(CommandCreateEntityObjectMultilines.java:63)
	at net.sourceforge.plantuml.command.CommandMultilines2.execute(CommandMultilines2.java:112)
	at net.sourceforge.plantuml.command.ProtectedCommand.execute(ProtectedCommand.java:57)
	at net.sourceforge.plantuml.AbstractPSystem.executeCommand(AbstractPSystem.java:186)
	at net.sourceforge.plantuml.command.PSystemCommandFactory.executeFewLines(PSystemCommandFactory.java:125)
	at net.sourceforge.plantuml.command.PSystemCommandFactory.createSystem(PSystemCommandFactory.java:108)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:160)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:188)
	at net.sourceforge.plantuml.servlet.DiagramResponse.getOutputBlockSelection(DiagramResponse.java:218)
	at net.sourceforge.plantuml.servlet.DiagramResponse.sendDiagram(DiagramResponse.java:186)
	at net.sourceforge.plantuml.servlet.UmlDiagramService.doDiagramResponse(UmlDiagramService.java:100)
	at net.sourceforge.plantuml.servlet.UmlDiagramService.doGet(UmlDiagramService.java:62)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
You should send a mail to plantuml@gmail.com or post to https://plantuml.com/qa with this log (V1.2024.3)
#
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
Aborted (core dumped)
```

**Comment by jerboaa** [comment]
Please report this to the folks providing you the `plantuml/plantuml-server:jetty` image. Instructions seem to be:

```
You should send a mail to plantuml@gmail.com or post to https://plantuml.com/qa with this log (V1.2024.3)
```

**Comment by kolchurinvv** [comment]
i've emailed them too. however the lines
```
#
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
Aborted (core dumped)
```
point here. this is why i've submitted here as well
