### ISSUE TITLE
Oceanblock 1.16.0 is crashing on startup

### ISSUE THREAD

**Issue by aVeGamingMaster** [adoptium/adoptium-support#1045]
### Please provide a brief summary of the bug

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9a4675130, pid=5816, tid=0x0000000000002394
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [glfw.dll+0x5130]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

1.Open FTB App
2.Launch Oceanblock
3.When game starts it instantly crashes

### Expected Results

Working Oceanblock

### Actual Results

Game can't start and crashes

### What Java Version are you using?

Java(TM) SE Runtime Environment (build 1.8.0_401-b10)

### What is your operating system and platform?

Windows 11 64x

### How did you install Java?

.exe installer

### Did it work before?

```Shell
It worked for some time
```

### Did you test with other Java versions?

```Shell
No, i didn't
```

### Relevant log output

```Shell
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
[Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
2024-03-23 18:45:40,680 main WARN Advanced terminal features are not available in this environment
[18:45:40] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, aVeGamingMaster, --version, 1.16.5-forge-36.2.39, --gameDir, C:\Users\furba\AppData\Local\.ftba\instances\1c6a5626-ecfe-45ff-8727-2ccfbf77d7a7, --assetsDir, C:\Users\furba\AppData\Local\.ftba\bin\assets, --assetIndex, 1.16, --uuid, 411eb341-653c-4a5a-9c40-1a6ea662f306, --accessToken, ????????, --userType, msa, --versionType, release, --width, 1720, --height, 840, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --fullscreen]
[18:45:40] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_312 by Temurin
[18:45:40] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18:45:41] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/furba/AppData/Local/.ftba/bin/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[18:45:41] [main/INFO] [STDOUT/]: [net.creeperhost.traylauncher.ModLocatorHack:<init>:32]: Initializing launcher communication
[18:45:41] [ForkJoinPool.commonPool-worker-9/INFO] [STDOUT/]: [net.creeperhost.traylauncher.LauncherCommunicator:lambda$connect$0:77]: Connected to launcher
[18:45:43] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
Init CreativeCore coremods ...
[18:45:48] [main/ERROR] [mixin/]: Mixin config minetogether.mixins.json does not specify "minVersion" property
[18:45:48] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[18:45:48] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.leobeliik.extremesoundmuffler.MixinConnector]
[18:45:48] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[18:45:48] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5-forge-36.2.39, --gameDir, C:\Users\furba\AppData\Local\.ftba\instances\1c6a5626-ecfe-45ff-8727-2ccfbf77d7a7, --assetsDir, C:\Users\furba\AppData\Local\.ftba\bin\assets, --uuid, 411eb341-653c-4a5a-9c40-1a6ea662f306, --username, aVeGamingMaster, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 1720, --height, 840, --fullscreen]
[18:45:48] [main/WARN] [mixin/]: Reference map 'miniutilities.refmap.json' for miniutilities.mixins.json could not be read. If this is a development environment you can ignore this message
[18:45:48] [main/WARN] [mixin/]: Reference map 'lemonlib.refmap.json' for lemonlib.mixins.json could not be read. If this is a development environment you can ignore this message
[18:45:48] [main/WARN] [mixin/]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[18:45:48] [main/INFO] [RoadRunner Early Loading/]: Loaded rule configuration file for RoadRunner: 81 options available, 2 override(s) found
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: updateFluidOnEyes net.minecraft.entity.Entity
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: getMaxAirSupply net.minecraft.entity.Entity
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: updateFluidHeightAndDoFluidPushing net.minecraft.entity.Entity
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: canBreatheUnderwater net.minecraft.entity.LivingEntity
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: decreaseAirSupply net.minecraft.entity.LivingEntity
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: increaseAirSupply net.minecraft.entity.LivingEntity
[18:45:49] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: travel net.minecraft.entity.LivingEntity
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: updateFogColor net.minecraft.client.renderer.FogRenderer
[18:45:49] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: getWaterBrightness net.minecraft.client.entity.player.ClientPlayerEntity
Injecting prior to return of setLoadingGui
[18:45:49] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching ModelBakery#<init>
[18:45:49] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[18:45:49] [main/WARN] [mixin/]: Error loading class: net/mrscauthd/boss_tools/events/OxygenSystem (java.lang.ClassNotFoundException: null)
[18:45:49] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.LivingEntityMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18:45:49] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.ServerWorldMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18:45:49] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.WorldChunkMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18:45:49] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.WorldMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18:45:49] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.goals.FleeEntityGoalMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18:45:49] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'ai.nearby_entity_tracking.goals.LookAtGoalMixin' as rule 'mixin.ai.nearby_entity_tracking' (added by user configuration) disables it and children
[18:45:49] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.chunk_ticking.ChunkTicketManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by user configuration) disables it and children
[18:45:49] [main/WARN] [RoadRunner Early Loading/]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by user configuration) disables it and children
[18:45:50] [main/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: turnPlayer net.minecraft.client.MouseHelper
[18:45:50] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching DataPackRegistries#<init>
[18:45:50] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LootTableManager#apply
[18:45:50] [main/INFO] [co.un.de.LoggerHacks/]: !!! SOME LOGGERS HAVE MOVED TO THE DEBUG FILE (Please Include them in your bug reports) !!!
[18:45:51] [pool-5-thread-1/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: updateFluidOnEyes net.minecraft.entity.Entity
[18:45:51] [pool-5-thread-1/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: getMaxAirSupply net.minecraft.entity.Entity
[18:45:51] [pool-5-thread-1/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: updateFluidHeightAndDoFluidPushing net.minecraft.entity.Entity
[18:45:51] [pool-5-thread-1/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: canBreatheUnderwater net.minecraft.entity.LivingEntity
[18:45:51] [pool-5-thread-1/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: decreaseAirSupply net.minecraft.entity.LivingEntity
[18:45:51] [pool-5-thread-1/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: increaseAirSupply net.minecraft.entity.LivingEntity
[18:45:51] [pool-5-thread-1/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[18:45:51] [pool-5-thread-1/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: travel net.minecraft.entity.LivingEntity
[18:45:52] [pool-5-thread-1/INFO] [FerriteCore - class definer/]: Using Java 8 class definer
[18:45:52] [pool-5-thread-1/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[18:45:53] [pool-5-thread-1/INFO] [FTB Janitor/]: Lazy DFU Loaded
Injecting prior to return of setLoadingGui
[18:45:55] [Render thread/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: getWaterBrightness net.minecraft.client.entity.player.ClientPlayerEntity
[18:45:55] [Render thread/INFO] [ne.mi.co.Co.better_diving/COREMODLOG]: Transforming method: getWaterBrightness net.minecraft.client.entity.player.ClientPlayerEntity
[18:45:56] [Render thread/INFO] [minecraft/Minecraft]: Setting user: aVeGamingMaster
[18:45:56] [Render thread/ERROR] [minecraft/GameSettings]: Failed to load options
java.lang.NumberFormatException: For input string: "key.keyboard.z"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_312] {}
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_312] {}
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_312] {}
	at net.minecraft.util.datafix.fixes.LWJGL3KeyOptions.func_209661_a(SourceFile:162) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_312] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_312] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_312] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_312] {}
	at net.minecraft.util.datafix.fixes.LWJGL3KeyOptions.func_209663_a_(SourceFile:183) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.datafix.fixes.LWJGL3KeyOptions.func_207424_a_(SourceFile:160) ~[?:?] {re:classloading}
	at com.mojang.datafixers.Typed.lambda$updateCap$9(Typed.java:164) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.util.Pair$Instance.traverse(Pair.java:90) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.optics.profunctors.TraversalP$1.lambda$wander$0(TraversalP.java:50) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.Typed.updateCap(Typed.java:164) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.Typed.update(Typed.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.Typed.update(Typed.java:133) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.datafix.fixes.LWJGL3KeyOptions.func_207423_a(SourceFile:159) ~[?:?] {re:classloading}
	at com.mojang.datafixers.DataFix.lambda$null$3(DataFix.java:86) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.types.Type.capWrite(Type.java:167) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.types.Type.lambda$readAndWrite$9(Type.java:159) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.types.Type.readAndWrite(Type.java:158) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:84) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.nbt.NBTUtil.func_210821_a(SourceFile:466) ~[?:?] {re:classloading}
	at net.minecraft.nbt.NBTUtil.func_210822_a(SourceFile:462) ~[?:?] {re:classloading}
	at net.minecraft.client.GameSettings.func_189988_a(GameSettings.java:572) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:OptionsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.GameSettings.func_74300_a(GameSettings.java:225) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:OptionsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.GameSettings.<init>(GameSettings.java:184) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:OptionsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.5-forge-36.2.39.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
[18:45:56] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.2.2 build 10
[18:45:56] [Render thread/INFO] [KubeJS/]: Loaded client.properties
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9a4675130, pid=5816, tid=0x0000000000002394
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [glfw.dll+0x5130]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\furba\AppData\Local\.ftba\instances\1c6a5626-ecfe-45ff-8727-2ccfbf77d7a7\hs_err_pid5816.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by tron359** [comment]
Apologies for commenting on this completed item. I encountered the same problem. I resolved it by changing the Java version **Prism**  uses to the most recent Java version. Before this, I had my prism launcher using v8, same as a modpack I was running. The modpack loaded after I updated the Prism launcher's java version and restarted Prism.
