### ISSUE TITLE
Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report. 

### ISSUE THREAD

**Issue by panther078** [adoptium/adoptium-support#1069]
## Question

Our user is trying to launch an on-demand application from the web using a downloaded .jnlp file. Upon launching, the user hit this error: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute Javaws/browser from the command line and send a bug report. 

Details:
net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:583)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:946)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:577)
	... 1 more
Caused by: com.kinaxis.web.ExceptionAdapter
	at com.kinaxis.web.ExceptionAdapter.wrap(ExceptionAdapter.java:15)
	at com.kinaxis.web.embeddedBrowser.ClientBridge.createCachePaths(ClientBridge.java:375)
	at com.kinaxis.web.embeddedBrowser.ClientBridge.initialize(ClientBridege.java:286)
        at com.kinaxis.web.WebStart.mail(WebStart,java:304
	... 6 more
Caused by: java.nio.file.AccessDeniedException:C:/Users/100053~2\AppData\Local\Temp
       at sun.nio.fs.WindwosException.transalteToIOException(WindowsException.java:83)
       at sun.nio.fs.WindwosException.rethrowAsIOException(WindowsException.java:97)
       at sun.nio.fs.WindwosException.rethrowAsIOException(WindowsException.java:102)
       at sun.nio.fs.WindwosFileSystemProvider.checkReadAccess(WindowsFileSystemProvider.java:338)
       at sun.nio.fs.WindwosFileSystemProvider.checkAccess(WindowsFileSystemProvider.java:362
       at java.nio.file.Files.createDirectories(Files.java:746)
       at com.kinaxis.web.embeddedBrowser.ClientBridge.createCachePaths(ClientBirdge.java:363)
      ...8 more

Upon checking further, this folder: C:/Users/**100053~2**\AppData\Local\Temp no longer existed. It should be redirected to C:/Users/**100053059**\AppData\Local\Temp

We have tried to purge all the cache and temp folders but we continue to hit the same error. 

Java version:

openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)

IcedTea WebStart
release 1.8.8

Your operating system and platform:
Windows 11 Enterprise

**Comment by karianna** [comment]
@panther078 please try with 1.8.0_412 and let us know if this still persists.

**Comment by panther078** [comment]
Hi @karianna,
Thank you. Wonder what is the root caused. We tried 1.8.0_412 as well and also hit the same issue. We are getting our internal IT to reprofile the user account from scratch to see if this helps.

**Comment by panther078** [comment]
Somehow, Java kept looking for  C:\Users\100053~2\AppData\Local\Temp which no longer existed.

Is there a way to edit the Java config to redirect to [C:\Users\100053059\AppData\Local\Temp?]

**Comment by karianna** [comment]
@hendrikebbers - perhaps you've seen this before?

**Comment by karianna** [comment]
@panther078 did you ever find a workaround
