### ISSUE TITLE
i can only install certain packs from curseforge why?

### ISSUE THREAD

**Issue by Zafwan2k** [adoptium/adoptium-support#1116]
### Please provide a brief summary of the bug

[20/06/2024 21:14:53 pm] java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "filesFound" is null
[20/06/2024 21:14:53 pm] 	at com.atlauncher.workers.InstanceInstaller.lambda$generatePackVersionFromCurseForgeManifest$7(InstanceInstaller.java:777)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
[20/06/2024 21:14:53 pm] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForgeManifest(InstanceInstaller.java:783)
[20/06/2024 21:14:53 pm] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForge(InstanceInstaller.java:989)
[20/06/2024 21:14:53 pm] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:309)
[20/06/2024 21:14:53 pm] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:139)
[20/06/2024 21:14:53 pm] 	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20/06/2024 21:14:53 pm] 	at java.base/java.lang.Thread.run(Unknown Source)
[20/06/2024 21:14:53 pm] java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "filesFound" is null

### Did you test with the latest update version?

- [X] Yes

### Expected Results

i installed the prominence 2 works fine while downloading at curseforge, others like bmc4 and fantasy mc fabric failed

### Actual Results

failed download

### What Java Version are you using?

JAVA 8

### What is your operating system and platform?

windows 10 pro x64

### How did you install Java?

comes with the atlauncher

### Did it work before?

```Shell
nevr tried
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
