### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by RMDanielMEx** [adoptium/adoptium-support#1175]
### Please provide a brief summary of the bug

Problem with new version of java 17.0.12 
t he error in the traceback indicates that there is a missing method in the ThemeReader class from the sun.awt.windows package. Specifically, the error is a NoSuchMethodError for the method :
void sun.awt.windows.ThemeReader.paintBackground(int[], java.lang.String, int, int, int, int, int, int, int)

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

any traceback

### Actual Results

java.lang.NoSuchMethodError: 'void sun.awt.windows.ThemeReader.paintBackground(int[], java.lang.String, int, int, int, int, int, int, int)' sun.awt.windows.ThemeReader.paintBackground(int[], java.lang.String, int, int, int, int, int, int, int)'
at com.jidesoft.plaf.windows.XPStyle$SkinPainter.paintToImage(XPStyle.java:645) ~[jide-common.jar:?]
at sun.swing.CachedPainter.getImage(CachedPainter.java:175) ~[?:?]
at sun.swing.CachedPainter$PainterMultiResolutionCachedImage.getResolutionVariant(CachedPainter.java:320) ~[?:?]
at sun.java2d.SunGraphics2D.getResolutionVariant(SunGraphics2D.java:3312) ~[?:?]
at sun.java2d.SunGraphics2D.drawHiDPIImage(SunGraphics2D.java:3140) ~[?:?]
at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3428) ~[?:?]
at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3412) ~[?:?]
at sun.swing.CachedPainter.paintImage(CachedPainter.java:249) ~[?:?]
at sun.swing.CachedPainter.paint0(CachedPainter.java:217) ~[?:?]
at sun.swing.CachedPainter.paint(CachedPainter.java:114) ~[?:?]
at com.jidesoft.plaf.windows.XPStyle$Skin.paintSkinRaw(XPStyle.java:591) ~[jide-common.jar:?]
at com.jidesoft.plaf.windows.XPStyle$Skin.paintSkin(XPStyle.java:576) ~[jide-common.jar:?]
at com.jidesoft.plaf.windows.XPStyle$Skin.paintSkin(XPStyle.java:550) ~[jide-common.jar:?]
at com.jidesoft.plaf.windows.WindowsIconFactory$CheckBoxIcon.paintIcon(WindowsIconFactory.java:73) ~[jide-common.jar:?]
at javax.swing.plaf.basic.BasicRadioButtonUI.paint(BasicRadioButtonUI.java:204) ~[?:?]
at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[?:?]
at javax.swing.JComponent.paintComponent(JComponent.java:842) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1119) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:170) ~[?:?]
at javax.swing.plaf.basic.BasicTreeUI.paintRow(BasicTreeUI.java:1788) ~[?:?]
at javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1429) ~[?:?]
at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[?:?]
at javax.swing.JComponent.paintComponent(JComponent.java:842) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1119) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JViewport.paint(JViewport.java:736) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JViewport.paint(JViewport.java:736) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintChildren(JComponent.java:952) ~[?:?]
at javax.swing.JComponent.paint(JComponent.java:1128) ~[?:?]
at javax.swing.JComponent.paintToOffscreen(JComponent.java:5311) ~[?:?]
at javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657) ~[?:?]
at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632) ~[?:?]
at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570) ~[?:?]
at javax.swing.RepaintManager.paint(RepaintManager.java:1337) ~[?:?]
at javax.swing.JComponent._paintImmediately(JComponent.java:5259) ~[?:?]
at javax.swing.JComponent.paintImmediately(JComponent.java:5069) ~[?:?]
at javax.swing.RepaintManager$4.run(RepaintManager.java:879) ~[?:?]
at javax.swing.RepaintManager$4.run(RepaintManager.java:862) ~[?:?]
at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862) ~[?:?]
at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835) ~[?:?]
at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784) ~[?:?]
at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898) ~[?:?]
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]

### What Java Version are you using?

17.0.12

### What is your operating system and platform?

Windows

### Did you test with other Java versions?

```Shell
in 17.0.8 works
```

**Comment by jerboaa** [comment]
The stack trace seems to indicate this is originating from a 3rd party LF:

```
java.lang.NoSuchMethodError: 'void sun.awt.windows.ThemeReader.paintBackground(int[], java.lang.String, int, int, int, int, int, int, int)' sun.awt.windows.ThemeReader.paintBackground(int[], java.lang.String, int, int, int, int, int, int, int)'
at com.jidesoft.plaf.windows.XPStyle$SkinPainter.paintToImage(XPStyle.java:645) ~[jide-common.jar:?]
```

Have you reported this to the `com.jidesoft` developers? Do you have a reproducer for this?
