### ISSUE TITLE
Java + Windows RDP disconnect causes Java Headless Exception

### ISSUE THREAD

**Issue by michael-newsrx** [adoptium/adoptium-support#1203]
### Please provide a brief summary of the bug

> I've also posted this at stackoverflow in case someone there can provide a short term work around. https://stackoverflow.com/q/79265762/1341731

Starting with Java 17.0.12 and 21.0.4 Java fails with a Headless exception when running a full GUI app via RDP and the RDP session is disconnected. The remote desktop is running and can be reconnected with. All non-Java apps are still running and updating their UI's just fine. It is only Java GUI apps that are crashing.

If the Java program attempts to do GUI operations such as create a modal progress bar while the RDP session is disconnected, a Headless exception is thrown, even though **the environment is not headless**, just disconnected.

This seems to be related to https://bugs.openjdk.org/browse/JDK-8340992 and https://bugs.openjdk.org/browse/JDK-8336862 but there are no workarounds provided.

Is there a workaround that can be done runtime?

The only workarounds we can come up with are:

1. Rewrite everything in another language. Not a small undertaking.
2. Downgrade all Java/JDK instances to 21.0.3 and not apply any security updates.
3. Lose all work and start over for any RDP disconnects caused by intentional user disconnect, internet issues, etc. This is where we are at now and it is causing production issues.

This would also seem to be breaking of the "contract" where minor point releases are not supposed to cause breaking changes.

We mostly use simple apps composed of `JFrames`, `JTextComponents`, and `ProgressMonitor` with a couple of self-hosted `JediTerm` applications.

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

Create an app with opens and closes windows with time delays.
Start the app on Windows in an RDP session.
Disconnect from the RDP session.
Wait till the app should have opened and closed any test windows.
Reconnect to the RDP session.

### Expected Results

The app to create UI components in the disconnected RDP session, just like all other non-Java apps are capable of.

### Actual Results

GUI apps should keep running when a remote desktop session is disconnected. They should not suddenly fail reporting that GUI operations are not possible.

### What Java Version are you using?

Picked up JAVA_TOOL_OPTIONS: -Xmx6144m -Dlog4j2.formatMsgNoLookups=true openjdk version "21.0.5" 2024-10-15 LTS OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing) PS C:\Users\admin.NEWSRX>

### What is your operating system and platform?

Windows specifications:

* Edition: Windows 10 Pro
* Version: 22H2
* Installed on: 2021-04-23
* OS build: 19045.5131
* 

### How did you install Java?

* AdoptOpenJDK

https://github.com/tushev/aojdk-updatewatcher/wiki

### Did it work before?

```Shell
Works with version 21.0.3
```

### Did you test with other Java versions?

```Shell
Every point release after 21.0.3 that AdoptOpenJDK reported in need of updating.
```

**Comment by michael-newsrx** [comment]
Code demonstrating issue:

```java
import javax.swing.*;
import java.awt.*;

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class Main {
    public static void main(String[] args) throws InterruptedException {
        var delay = 10;
        var isHeadless = GraphicsEnvironment.isHeadless();
        System.out.printf("1) Is headless: %s.%n", isHeadless);
        System.out.printf("Sleeping %,d seconds.%n", delay);
        System.out.printf("""
                DISCONNECT YOUR REMOTE DESKTOP CONNECTION NOW!
                RECONNECT AFTER %,d SECONDS.
                """, delay);
        Thread.sleep(delay * 1_000);
        System.out.println("Drawing progress bar");
        ProgressMonitor p = new ProgressMonitor(null, "Test progressbar", "My note", 0, 100);
        for (int i = 0; i < 100; i++) {
            p.setProgress(i);
            Thread.sleep(250);
        }
        isHeadless = GraphicsEnvironment.isHeadless();
        System.out.printf("2) Is headless: %s.%n", isHeadless);

        //TIP Press <shortcut actionId="ShowIntentionActions"/> with your caret at the highlighted text
        // to see how IntelliJ IDEA suggests fixing it.
        System.out.printf("Hello and welcome!");

        for (int i = 1; i <= 5; i++) {
            //TIP Press <shortcut actionId="Debug"/> to start debugging your code. We have set one <icon src="AllIcons.Debugger.Db_set_breakpoint"/> breakpoint
            // for you, but you can always add more by pressing <shortcut actionId="ToggleLineBreakpoint"/>.
            System.out.println("i = " + i);
        }
    }
}
```

Error log:

```java
"C:\Program Files\Eclipse Adoptium\jdk-21.0.5.11-hotspot\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2024.3.1\lib\idea_rt.jar=59072:C:\Program Files\JetBrains\IntelliJ IDEA 2024.3.1\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath C:\Users\admin.NEWSRX\git\rdp-crashes\out\production\rdp-crashes Main
Picked up JAVA_TOOL_OPTIONS: -Xmx6144m -Dlog4j2.formatMsgNoLookups=true
1) Is headless: false.
Sleeping 10 seconds.
DISCONNECT YOUR REMOTE DESKTOP CONNECTION NOW!
RECONNECT AFTER 10 SECONDS.
Drawing progress bar
Exception in thread "main" java.awt.AWTError: no screen devices
	at java.desktop/sun.awt.Win32GraphicsEnvironment.getDefaultScreenDevice(Win32GraphicsEnvironment.java:101)
	at java.desktop/sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:157)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:274)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1242)
	at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1700)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:360)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getPreferredSize(BasicButtonUI.java:542)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getMinimumSize(BasicButtonUI.java:532)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1814)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:818)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:751)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:206)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:160)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
	at java.desktop/javax.swing.JOptionPane.setUI(JOptionPane.java:1858)
	at java.desktop/javax.swing.JOptionPane.updateUI(JOptionPane.java:1880)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1845)
	at java.desktop/javax.swing.ProgressMonitor$ProgressOptionPane.<init>(ProgressMonitor.java:161)
	at java.desktop/javax.swing.ProgressMonitor.setProgress(ProgressMonitor.java:291)
	at Main.main(Main.java:20)

Process finished with exit code 1
```

**Comment by jerboaa** [comment]
Looks to be https://bugs.openjdk.org/browse/JDK-8336862

Does setting `-Djava.awt.headless=false` help?

**Comment by michael-newsrx** [comment]
No this does not help.

```java
"C:\Program Files\Eclipse Adoptium\jdk-21.0.5.11-hotspot\bin\java.exe" -Djava.awt.headless=false "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2024.3.1\lib\idea_rt.jar=59410:C:\Program Files\JetBrains\IntelliJ IDEA 2024.3.1\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath C:\Users\admin.NEWSRX\git\rdp-crashes\out\production\rdp-crashes Main
Picked up JAVA_TOOL_OPTIONS: -Xmx6144m -Dlog4j2.formatMsgNoLookups=true
1) Is headless: false.
Sleeping 10 seconds.
DISCONNECT YOUR REMOTE DESKTOP CONNECTION NOW!
RECONNECT AFTER 10 SECONDS.
Drawing progress bar
Exception in thread "main" java.awt.AWTError: no screen devices
	at java.desktop/sun.awt.Win32GraphicsEnvironment.getDefaultScreenDevice(Win32GraphicsEnvironment.java:101)
	at java.desktop/sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:157)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:274)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1242)
	at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1700)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:360)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getPreferredSize(BasicButtonUI.java:542)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getMinimumSize(BasicButtonUI.java:532)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1814)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:818)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:751)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:206)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:160)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:740)
	at java.desktop/javax.swing.JOptionPane.setUI(JOptionPane.java:1858)
	at java.desktop/javax.swing.JOptionPane.updateUI(JOptionPane.java:1880)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1845)
	at java.desktop/javax.swing.ProgressMonitor$ProgressOptionPane.<init>(ProgressMonitor.java:161)
	at java.desktop/javax.swing.ProgressMonitor.setProgress(ProgressMonitor.java:291)
	at Main.main(Main.java:20)

Process finished with exit code 1
```

**Comment by michael-newsrx** [comment]
Hrmmmm... just tried using JetBrains JDK in Intellij version 21.0.5 and the problem does not occur.

**Comment by michael-newsrx** [comment]
OK

So we've downgraded all the physical desktop systems to 21.0.3 and the RDP disconnect no longer cause Java to crash.

As we use AdoptOpenJDK, we told it to skip the current 21.0.5 release for updating.

-Mike/NewsRx

**Comment by mjschwaiger** [comment]
> Hrmmmm... just tried using JetBrains JDK in Intellij version 21.0.5 and the problem does not occur.

The reason why this works in JetBrains Runtime (JBR) is because the problem has been solved directly in JBR.
Changes from JDK-8336862 have been undone. See JBR-7683 and commit bb54739.
* https://youtrack.jetbrains.com/issue/JBR-7683
* https://github.com/JetBrains/JetBrainsRuntime/commit/bb54739eb242dc32b2acd369199eef3c6ca435eb
Seems to work again with JBR 21.0.5 b709 and later.

However, there are no changes to the OpenJDK at the present time.
* https://bugs.openjdk.org/browse/JDK-8336862
* https://bugs.openjdk.org/browse/JDK-8185862

Currently, the only known workaround is to stick with Java 21.0.3 (Java 17.0.11). However, as it does not provide fixes for new vulnerabilities and other issues, it is not a long-term solution.

**Comment by RealCLanger** [comment]
I'm working on a backout of [JDK-8185862](https://bugs.openjdk.org/browse/JDK-8185862):  [JDK-8348625](https://bugs.openjdk.org/browse/JDK-8348625)

**Comment by plexiq** [comment]
We have several customers affected by this issue on an eclipse RCP based application + RDP.

Are there currently any fixes for Java 23/24 in the works as well?

**Comment by RealCLanger** [comment]
> We have several customers affected by this issue on an eclipse RCP based application + RDP.
> 
> Are there currently any fixes for Java 23/24 in the works as well?

I will have a look at this. I think the RDP issue can be addressed.

**Comment by RealCLanger** [comment]
> [@RealCLanger](https://github.com/RealCLanger): Thanks for reverting the changes of the issue [JDK-8185862](https://bugs.openjdk.org/browse/JDK-8185862) in issue [JDK-8348625](https://bugs.openjdk.org/browse/JDK-8348625) (see [1359](https://github.com/openjdk/jdk21u-dev/pull/1359)) for JDK 21 (jdk21u-dev).
> 
> [@GoeLin](https://github.com/GoeLin): What are the next steps to ensure that these changes are also included in JDK 17 (jdk17u-dev)? Will JDK 17 have a separate backport issue? We hope this will happen in time for the next release update in April 2025 (JDK 17.0.15).

No worries, I'm working on the backort to jdk17u, in time for the April update. 😄

**Comment by jerboaa** [comment]
> Thanks for reverting the changes of the issue [JDK-8185862](https://bugs.openjdk.org/browse/JDK-8185862) in issue [JDK-8348625](https://bugs.openjdk.org/browse/JDK-8348625) (see [1359](https://github.com/openjdk/jdk21u-dev/pull/1359)) for JDK 21 (jdk21u-dev).

In the meantime, please test JDK 21 ea builds (e.g. from Temurin) to see if the issues you see are gone:

https://api.adoptium.net/v3/binary/latest/21/ea/windows/x64/jdk/hotspot/normal/eclipse

This should get you an `21.0.7+1` build (which has the fix) in the next couple of days.

**Comment by mjschwaiger** [comment]
Already tested today with both `jdk-21.0.6+7-jre` and `jdk-21.0.7+1-jre`.

The problem can be reproduced using `jdk-21.0.6+7-jre`.
But the issue is not reproducible with `jdk-21.0.7+1-jre`.

The following build was used for this test:
* Platfrom: Windows x64
* Type: JRE
* Build: 21.0.7-beta+1-ea
* Date: 2025-02-10
* Source: https://adoptium.net/de/temurin/nightly/

**Comment by jerboaa** [comment]
Thanks for testing! We'll close this issue once the 21.0.7 and 17.0.15 releases are done.

**Comment by jerboaa** [comment]
Most 21.0.7 and 17.0.15 releases have shipped now. Closing.

**Comment by pauldaustin** [comment]
I'm having this issue on Java 25. 

The main problem is that Azure Bastion RDP connections disconnect you when the screen locks. So if you're running a long task and your organization locks the screen every 15 minutes you run the risk of the Java app crashing part way through a process.

**Comment by andrewauclair** [comment]
Another two months have come and gone, and I don't see any progress on this issue for Java 25. It's rather irritating that this was such a big issue in the older releases, patched, and then Java 25 was released with the same issues.

**Comment by pquiring** [comment]
Resubmitted a bug request to Oracle. ID # 167347da-a2d0-415b-9c0c-809e69ad2043

**Comment by michael-newsrx** [comment]
> Another two months have come and gone, and I don't see any progress on this issue for Java 25. It's rather irritating that this was such a big issue in the older releases, patched, and then Java 25 was released with the same issues.

It's seems to be an upstream `Oracle` ignored problem - and this need for downstream patching is causing a drift problem I'm sure.

**Comment by karianna** [comment]
I think related is: https://bugs.openjdk.org/browse/JDK-8341294 which looks like it has a 27 fix and possible backportds - CC  @RealCLanger -

**Comment by RealCLanger** [comment]
> I think related is: https://bugs.openjdk.org/browse/JDK-8341294 which looks like it has a 27 fix and possible backportds - CC [@RealCLanger](https://github.com/RealCLanger) -

No, sorry, there is no fix for this. My colleague tried but it was not possible to make progress here with Oracle experts chiming in.

**Comment by andrewauclair** [comment]
The one I'm interested in is https://bugs.openjdk.org/browse/JDK-8336862. Which I just noticed has a listed fixed version. I did not notice that before. Claims to be fixed in 27.

**Comment by RealCLanger** [comment]
> The one I'm interested in is https://bugs.openjdk.org/browse/JDK-8336862. Which I just noticed has a listed fixed version. I did not notice that before. Claims to be fixed in 27.

That one also isn't fixed, it is still "Unresolved"

**Comment by mjschwaiger** [comment]
This issue with RDP on Windows and the breaking changes regarding LocaleServiceProvider ([JDK-8325568](https://bugs.openjdk.org/browse/JDK-8325568) and [JEP 252](https://openjdk.org/jeps/252)) are the biggest stumbling blocks preventing us from updating to Java 25.

**Comment by liamsharp** [comment]
We've just updated our product to Java 25 and released it this week - we're getting lots of reports of this, any plans to fix for 25?

**Comment by karianna** [comment]
FYI - A fix for 25 will depend on a volunteer from the OpenJDK community applying that fix upstream.  There are also commercial support options if you want a guaranteed time/fix (https://adoptium.net/en-GB/temurin/commercial-support).

**Comment by RealCLanger** [comment]
FWIW: There's something going on in https://bugs.openjdk.org/browse/JDK-8341382. Maybe this will help and can then certainly be backported to 25.

https://git.openjdk.org/jdk/pull/31238

**Comment by pauldaustin** [comment]
I find it odd that JDK 25 is the long term release and that critical bug fixes are created in later releases and then back ported.

As a developer I find it a lot easier to fix bugs in an older version and then merge those into to later releases.

**Comment by matthieu-labas** [comment]
FWIW JetBrains made a correction in their [JetBrainsRuntime](https://github.com/JetBrains/JetBrainsRuntime) (OpenJDK fork), available for Java 25 in their [GitHub releases](https://github.com/JetBrains/JetBrainsRuntime/releases).

I just tested it now and, while OpenJDK 26 showed me the error (crashing my Swing apps), JBR 25.0.3b508.16 didn't.
Big kudos to them 🥇

**Comment by jerboaa** [comment]
This will be fixed in JDK 25.0.5 (October, 2026).

**Comment by fmarot** [comment]
Hi, does anyone know if the fix will solve the same problem but with SSH session on windows ? (my unit tests with Jenkins connected to Windows through SSH were ok in Java 21 but ko with Java 25)

**Comment by jerboaa** [comment]
For JDK 25, you'll have to wait for the October release or try an EA build from: https://adoptium.net/en-GB/temurin/nightly?version=25

**Comment by fmarot** [comment]
> Hi, does anyone know if the fix will solve the same problem but with SSH session on windows ? (my unit tests with Jenkins connected to Windows through SSH were ok in Java 21 but ko with Java 25)

thanks @jerboaa , I tested with early builds of the october release and it solves the "Headless mode is forced on windows when Jenkins is connected through SSH" behavior change I was facing in JDK 25.

**Comment by jerboaa** [comment]
Thanks for the feedback. We'll close the issue once the release is GA.
