### ISSUE TITLE
ImageIcon on HotSpot builds after jdk-11.0.6+10

### ISSUE THREAD

**Issue by devilsclaw** [adoptium/adoptium-support#255]
* **Browser**:

I have a problem that exists in all release versions after jdk-11.0.6+10 HotSpot, the problem does not exist in the OpenJ9 releases.

NOTE: Only talking about 11 LTS builds have not tried anything above the 11 LTS
NOTE2: This is the Windows 64Bit and X86 versions I have tested.

java.util.List<Image> icons = new ArrayList<>();
ImageIcon icon = new ImageIcon(getClass().getResource("/images/sys_icon.gif"));
Image image = icon.getImage();
icons.add(image);
setIconImages(icons);

I have debugged the code to rule out that its not pathing. I did this by switching getResource to getResourceAsStream and printing out all the bytes of the image.

The problem is at creating a new  ImageIcon. 
 
It throws
Exception in thread "main" java.lang.ExceptionInInitializerError

I tried merging the working version with a non working version by copying over the conf, lib.

I get this
Exception in thread "main" java.lang.NoSuchMethodError: notifyWindowStateChanged
        at java.desktop/sun.awt.windows.WWindowPeer.initIDs(Native Method)
        at java.desktop/sun.awt.windows.WWindowPeer.<clinit>(Unknown Source)
        at java.desktop/sun.awt.windows.WToolkit.createFrame(Unknown Source)
        at java.desktop/java.awt.Frame.addNotify(Unknown Source)
        at java.desktop/java.awt.Window.pack(Unknown Source)
        at estDiscover.frmAbout.initComponents(frmAbout.java:65)
        at estDiscover.frmAbout.<init>(frmAbout.java:18)
        at estDiscover.estDiscover.<init>(estDiscover.java:98)
        at estDiscover.main.main(main.java:136)

I know that is non standard just testing.

The next thing i did was copy over awt.dll, jawt.dll, jimage.dll and the program got passed the failed to create the imageicon problem.

**Comment by aahlenst** [comment]
Please create a main class (file with `public static void main(String[] args)` function) that reproduces your problem.

**Comment by devilsclaw** [comment]
I found what I think are bugs/regression in HotSpot JVM vs the OpenJ9

1) System.setProperty("java.library.path",path); is ignored by all version of HotSpot 11 LTS
2) Runtime.getRuntime().load(lib); not taking absolute paths on all versions of HotSpot 11 LTS
3) Messing with sys_paths via reflection which what is being done is considered bad and not to work in the future still works and does not behave like OpenJ9 or version HotSpot jdk-11.0.6+10

```
package openjdk11_hotspot_bug;

import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;

public class OpenJDK11_HotSpot_Bug extends javax.swing.JFrame {
  private static final Object mutex = new Object();
  public  static final String EXTRACT_PATH;
  private static boolean extract_path_created = false;
  public  static final String ARCH;
  public  static final String OS;

  static {
    ARCH = get_arch_type();
    OS = System.getProperty( "os.name" ).toLowerCase();
    EXTRACT_PATH = System.getProperty("java.io.tmpdir") + File.separator + "natives" + new Random().nextInt();
    Runtime.getRuntime().addShutdownHook(new Thread() {
      @Override
      public void run() {
        synchronized(mutex) {
          if(!extract_path_created) {
            return;
          }
          File path = new File(EXTRACT_PATH);
          if(path.exists()) {
            File[] files = path.listFiles();
            for(File file : files) {
              file.delete();
            }
            path.delete();
          }
        }
      }
    });
    if(OS.toLowerCase().startsWith("windows")) {
      String resource_path = "/natives/windows";
      if(ARCH.equals("32")) {
        extract_resource(String.format("%s/%s/%s",resource_path,ARCH,"ProjectDLL.dll"),EXTRACT_PATH);
        extract_resource(String.format("%s/%s/%s",resource_path,ARCH,"ProjectDLL.dll"),EXTRACT_PATH);
      } else if(ARCH.equals("64")) {
        extract_resource(String.format("%s/%s/%s",resource_path,ARCH,"ProjectDLL.dll"),EXTRACT_PATH);
      }
    } else if(OS.equals("linux")) {
    }
  };

  public static boolean extract_resource(String res, String dest) {
    File dir = new File(EXTRACT_PATH);
    synchronized(mutex) {
      if (!extract_path_created && !dir.exists()) {
        if(dir.mkdirs()) {
          extract_path_created = true;
        } else {
          return false;
        }
      }
    }

    try {
      String[] s = res.split("/");
      OutputStream out;
      System.out.println("res: " + res + "\ndes: " + dest + File.separator + s[s.length-1]);
      try (InputStream in = mutex.getClass().getResourceAsStream(res)) {
        out = new FileOutputStream(dest + File.separator + s[s.length-1]);
        byte[] buffer = new byte[4096];
        int bufferSize;
        while((bufferSize = in.read(buffer,0,buffer.length)) != -1) {
          out.write(buffer,0,bufferSize);
        }
        out.close();
      }
    } catch (IOException e) {
      return false;
    }
    return true;
  }

  public static void update_lib_path(String path) {
    System.setProperty("java.library.path",path);
  }

  public static void update_lib_path2(String path) {
    System.setProperty("java.library.path",path);
      try {
      Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
      fieldSysPath.setAccessible(true);
      fieldSysPath.set(null,null);
    } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
    }
  }

  public static void load_library(String library) {
    String ext = "";
    if(OS.toLowerCase().startsWith("windows")) {
      ext = ".dll";
    } else if(OS.toLowerCase().equals("linux")) {
      ext = ".so";
    }
    System.out.print(String.format("%s%s%s .. ", EXTRACT_PATH,library,ext));
    Runtime.getRuntime().loadLibrary(library);
    System.out.println("OK");
  }

  public static void load_library(String path,String library) {
    String ext = "";
    String lib = "";
    if(OS.toLowerCase().startsWith("windows")) {
      ext = ".dll";
    } else if(OS.toLowerCase().equals("linux")) {
      ext = ".so";
    }

    lib = String.format("%s%s%s%s", path,File.separator,library,ext);

    System.out.print(String.format("%s%s .. ", library,ext));
    Runtime.getRuntime().load(lib);
    System.out.println("OK");
  }

  public static String get_arch_type() {
    String os = System.getProperty("os.name").toLowerCase();
    String realArch = "";
    if(os.toLowerCase().startsWith("Windows")) {
      String arch = System.getenv("PROCESSOR_ARCHITECTURE");
      String wow64Arch = System.getenv("PROCESSOR_ARCHITEW6432");
      realArch = arch.endsWith("64") || wow64Arch != null && wow64Arch.endsWith("64") ? "64" : "32";
    } else {
      realArch = System.getProperty("os.arch").contains("64") ? "64" : "32";
      realArch = System.getProperty("os.arch").contains("arm") ? "arm" : realArch;
    }
    System.out.println("arch type: " + realArch);
    return realArch;
  }

  public OpenJDK11_HotSpot_Bug() {
    initComponents();

    //This works on OpenJ9 but not HotSpot 
    update_lib_path(EXTRACT_PATH);

    load_library("ProjectDLL");
    load_library(EXTRACT_PATH,"ProjectDLL");

    //This will cause the new ImageIcon to break for everything after version jdk-11.0.6+10 of HotSpot but works on OpenJ9
    //update_lib_path2(EXTRACT_PATH);

    java.util.List<Image> icons = new ArrayList<>();
    ImageIcon icon = new ImageIcon(getClass().getResource("/images/sys_icon.gif"));
    Image image = icon.getImage();
    icons.add(image);
    setIconImage(image);
    
    icons = new ArrayList<>();
    icon = new ImageIcon(getClass().getResource("/images/button_image.gif"));
    image = icon.getImage();
    icons.add(image);
    jButton1.setIcon(icon);
  }

  @SuppressWarnings("unchecked")                       
  private void initComponents() {

    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setPreferredSize(new java.awt.Dimension(148, 35));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    pack();
  }// </editor-fold>                        

  public static void main(String args[]) {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(OpenJDK11_HotSpot_Bug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new OpenJDK11_HotSpot_Bug().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify                     
  private javax.swing.JButton jButton1;
  // End of variables declaration                   
}
```

Here is the project zipped up with the needed files and the source code for the dlls

[https://drive.google.com/file/d/1QJFw0Ng79JMWvVr0iiY1dj5-tCdvVgCL/view?usp=sharing](url)

**Comment by aahlenst** [comment]
There's a lot going on in your sample and it does not help that you included code to handle platfrom differences while the problem should only happen on Windows. Please reduce your samples as far as possible and concentrate on one potential problem per sample.

That something works with OpenJ9 while it does not in OpenJDK is not necessarily a problem of the latter.

**Comment by aahlenst** [comment]
Your problem seems to be with the core libraries, so unlikely caused by us. If you can reproduce the problem with Oracle JDK, you can try your luck on https://bugreport.java.com/bugreport/, but do not mention OpenJ9.

**Comment by devilsclaw** [comment]
From my understanding, one JVM should act like another JVM in respect of functionality, performance can be different but in most respects they should behave the same, otherwise what is the point of having a standard.

I reduced it further the only other way I could reduce it more is have the files pre-extracted in a sub directory and point the path there.

If that is what you need / want I can do that

```
package openjdk11_hotspot_bug;

import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;

public class OpenJDK11_HotSpot_Bug extends javax.swing.JFrame {
  private static final Object mutex = new Object();
  public  static final String EXTRACT_PATH;

  static {
    //Generate a temp directory path
    EXTRACT_PATH = System.getProperty("java.io.tmpdir") + File.separator + "natives" + new Random().nextInt();
    
    //Windows 32
    //extract_resource(String.format("/natives/windows/32/ProjectDLL.dll"),EXTRACT_PATH);
    //Windows 64
    extract_resource(String.format("/natives/windows/64/ProjectDLL.dll"),EXTRACT_PATH);
  };

  public static boolean extract_resource(String res, String dest) {
    //Create The temp directory for our resources if it does not exist
    File dir = new File(EXTRACT_PATH);
    synchronized(mutex) {
      if (!dir.exists()) {
        if(!dir.mkdirs()) {
          return false;
        }
      }
    }

    //Write the file to the temp location
    try {
      String[] s = res.split("/");
      OutputStream out;
      try (InputStream in = mutex.getClass().getResourceAsStream(res)) {
        out = new FileOutputStream(dest + File.separator + s[s.length-1]);
        byte[] buffer = new byte[4096];
        int bufferSize;
        while((bufferSize = in.read(buffer,0,buffer.length)) != -1) {
          out.write(buffer,0,bufferSize);
        }
        out.close();
      }
    } catch (IOException e) {
      return false;
    }
    return true;
  }

  public static void update_lib_path(String path) {
    System.setProperty("java.library.path",path);
  }

  public static void update_lib_path2(String path) {
    System.setProperty("java.library.path",path);
    try {
      Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
      fieldSysPath.setAccessible(true);
      fieldSysPath.set(null,null);
    } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
    }
  }

  public static void load_library(String library) {
    Runtime.getRuntime().loadLibrary(library);
  }

  public static void load_library(String path,String library) {
    Runtime.getRuntime().load(path + "\\" + library + ".dll");
  }

  public OpenJDK11_HotSpot_Bug() {
    initComponents();

    //This works on OpenJ9 but not HotSpot 
    update_lib_path(EXTRACT_PATH);

    load_library("ProjectDLL");
    load_library(EXTRACT_PATH,"ProjectDLL");

    //This will cause the new ImageIcon to break for everything after version jdk-11.0.6+10 of HotSpot but works on OpenJ9
    //update_lib_path2(EXTRACT_PATH);

    java.util.List<Image> icons = new ArrayList<>();
    ImageIcon icon = new ImageIcon(getClass().getResource("/images/sys_icon.gif"));
    Image image = icon.getImage();
    icons.add(image);
    setIconImage(image);
    
    icons = new ArrayList<>();
    icon = new ImageIcon(getClass().getResource("/images/button_image.gif"));
    image = icon.getImage();
    icons.add(image);
    jButton1.setIcon(icon);
  }
```

**Comment by karianna** [comment]
It depends on whether this functionality is covered by the TCK or not (we won't know if we trip that until we get to Eclipse as part of our move).  I'd recommend submitting your issue to 2d-dev AT openjdk DOT NET (I'd avoid any mention of OpenJ9 there).

**Comment by karianna** [comment]
@devilsclaw Are you able to try with the latest 11.0.15?
