### ISSUE TITLE
Connecting to JMX over RMI results in "java.lang.SecurityException: attempt to add a Permission to a readonly Permissions object"

### ISSUE THREAD

**Issue by gjd6640** [adoptium/adoptium-support#261]
## Summary

Installing a SecurityManager and a custom Policy implementation results in "java.lang.SecurityException: attempt to add a Permission to a readonly Permissions object" when connecting over RMI (from JVisualVM or Mission Control).

[This issue in the OpenJDK project](https://bugs.openjdk.java.net/browse/JDK-8014008) seems to refer to the same behavior. Note that they seem to lack info on how to reproduce the behavior which I'm including below.

## Steps to reproduce

0) Edit the attached "DisallowSystemExitCallSecurityManager" Java Class by block commenting the getPermissions() method implementation. That's a hack that works around the root problem...

[DisallowSystemExitCallSecurityManager.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/5992378/DisallowSystemExitCallSecurityManager.zip)

1) Call static method "DisallowSystemExitCallSecurityManager.installMe()" which aims to prevent child classloaders from successfully calling System.exit().

2) Thread.sleep() for a long time so that the JVM will stay running

3) Use Mission Control or JConsole to connect to the JMX MBeanServer. You don't need to expose a remote port. Just let the tool detect the pid and perform a local port-less connection.
Note: The same issue occurs when you try to connect via an exposed JMX port.

4) Observe that your connection failed in step 3 with a stack trace.
- In JVisualVM the error shown is vague and you have to go to "About" and view the logs from there. Mission Control makes it easy to see the stack trace.

## Expected results

Successfully open a connection via JMX / be able to browse MBeans.

## Actual results

com.jrockit.mc.rjmx.ConnectionException caused by java.lang.SecurityException: attempt to add a Permission to a readonly Permissions object
	at com.jrockit.mc.rjmx.internal.RJMXConnection.connect(RJMXConnection.java:554)
	at com.jrockit.mc.rjmx.ServerHandle.doConnect(ServerHandle.java:89)
	at com.jrockit.mc.rjmx.ServerHandle.connect(ServerHandle.java:70)
	at com.jrockit.mc.browser.wizards.ConnectionWizardPage$ConnectionTester.run(ConnectionWizardPage.java:780)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.SecurityException: attempt to add a Permission to a readonly Permissions object
	at java.security.Permissions.add(Permissions.java:126)
	at java.security.Policy$UnsupportedEmptyCollection.add(Policy.java:827)
	at sun.rmi.server.LoaderHandler.getLoaderAccessControlContext(LoaderHandler.java:1005)
	at sun.rmi.server.LoaderHandler.lookupLoader(LoaderHandler.java:881)
	at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:404)
	at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:186)
	at java.rmi.server.RMIClassLoader$2.loadClass(RMIClassLoader.java:637)
	at java.rmi.server.RMIClassLoader.loadClass(RMIClassLoader.java:264)
	at sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:219)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1923)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1806)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1985)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:465)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:423)
	at sun.rmi.server.UnicastRef.unmarshalValue(UnicastRef.java:327)
	at sun.rmi.server.UnicastServerRef.unmarshalParametersChecked(UnicastServerRef.java:650)
	at sun.rmi.server.UnicastServerRef.unmarshalParameters(UnicastServerRef.java:616)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:338)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	at com.sun.proxy.$Proxy25.newClient(Unknown Source)
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308)
	at com.jrockit.mc.rjmx.internal.RJMXConnection.connectJmxConnector(RJMXConnection.java:602)
	at com.jrockit.mc.rjmx.internal.RJMXConnection.establishConnection(RJMXConnection.java:578)
	at com.jrockit.mc.rjmx.internal.RJMXConnection.connect(RJMXConnection.java:546)
	... 4 more

## Triaging info

Java version:

AdoptOpenJDK version: jdk8u282

What is your operating system and platform?

CentOS6

How did you install Java?

RPM

Did it work before?

I've never seen this work. This is the first time I've needed to use a SecurityManager and custom Policy.

Did you test with other Java versions?

The same issue occurs on Oracle JDK v1.8.0_121

**Comment by andrew-m-leonard** [comment]
Updated bug with reproduce info: https://bugs.openjdk.java.net/browse/JDK-8014008?focusedCommentId=14402666&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14402666

**Comment by karianna** [comment]
Still an open issue upstream

**Comment by karianna** [comment]
Still an open issue upstream

**Comment by karianna** [comment]
As this has been reported upstream I'm closing this issue.
