### ISSUE TITLE
JShell is not working with Java 15 (StringIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by bennetelli** [adoptium/adoptium-support#267]
## Summary

A brief summary of the problem.
Since Java 15.0.0 jshell seems to broken. I tried every Java 15 release. JDK 15.0.0, 15.0.1 and 15.0.2 with HotSpot as well as with J9.
When using one of these releases and trying to call the "jshell" command, I get an excrption (see actual result section.

## Steps to reproduce

I downloaded sdkman to switch between java versions easily.

1. sdk use java  15.0.0.hs-adpt 
2. call "jshell" in the console
3. get the stacktrace above

## Expected results

I expect jshell to behave as Java 14.0.2 does. So that I can just use jshell without exceptions.
When using java 14 by calling: sdk use java 14.0.2.hs-adpt, the jshell command behaves as expected and I can use it without getting exceptions.

## Actual results

Exception in thread "main" java.io.IOError: java.lang.StringIndexOutOfBoundsException
	at jdk.internal.le/jdk.internal.org.jline.utils.Curses.tputs(Curses.java:62)
	at jdk.internal.le/jdk.internal.org.jline.utils.Curses.tputs(Curses.java:45)
	at jdk.internal.le/jdk.internal.org.jline.keymap.KeyMap.key(KeyMap.java:243)
	at jdk.internal.le/jdk.internal.org.jline.reader.impl.LineReaderImpl.key(LineReaderImpl.java:6095)
	at jdk.internal.le/jdk.internal.org.jline.reader.impl.LineReaderImpl$$Lambda$369/0x0000000064833110.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at jdk.internal.le/jdk.internal.org.jline.reader.impl.LineReaderImpl.bindKeys(LineReaderImpl.java:6103)
	at jdk.internal.le/jdk.internal.org.jline.reader.impl.LineReaderImpl.emacs(LineReaderImpl.java:5813)
	at jdk.internal.le/jdk.internal.org.jline.reader.impl.LineReaderImpl.defaultKeyMaps(LineReaderImpl.java:5789)
	at jdk.internal.le/jdk.internal.org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:293)
	at jdk.jshell/jdk.internal.jshell.tool.ConsoleIOContext$2.<init>(ConsoleIOContext.java:133)
	at jdk.jshell/jdk.internal.jshell.tool.ConsoleIOContext.<init>(ConsoleIOContext.java:133)
	at jdk.jshell/jdk.internal.jshell.tool.JShellTool.start(JShellTool.java:978)
	at jdk.jshell/jdk.internal.jshell.tool.JShellToolBuilder.start(JShellToolBuilder.java:254)
	at jdk.jshell/jdk.internal.jshell.tool.JShellToolProvider.main(JShellToolProvider.java:120)
Caused by: java.lang.StringIndexOutOfBoundsException
	at java.base/java.lang.String.charAt(String.java:1334)
	at jdk.internal.le/jdk.internal.org.jline.utils.Curses.doTputs(Curses.java:359)
	at jdk.internal.le/jdk.internal.org.jline.utils.Curses.tputs(Curses.java:60)
	... 22 more

## Triaging info

Java version:

Every Java 15 version

What is your operating system and platform?

My OS is Manjaro Linux x64.

How did you install Java?

via sdkman.https://sdkman.io/

Did it work before?

It worked with Java 14 and below.

Did you test with other Java versions?

Yes.

**Comment by aahlenst** [comment]
Is it https://bugs.openjdk.java.net/browse/JDK-8261450?

**Comment by bennetelli** [comment]
@aahlenst I think it's a similar issue but not the same issue. I don't even get into the jshell in my case.

**Comment by bennetelli** [comment]
I just did a comparison with a colleague. He is using Mac OS and I'm on Manjaro Linux. The jshell of OpenJDK 15.0.2 is working fine on his notebook while I'm still getting the exceptions above.

**Comment by aahlenst** [comment]
@bennetelli Can you check with 15.0.2 from https://adoptopenjdk.net/?variant=openjdk15&jvmVariant=hotspot? Looks like you're still using 15.0.0. If it doesn't work, test with https://adoptopenjdk.net/nightly.html?variant=openjdk16&jvmVariant=hotspot. And please do the same with 15 and 16 from https://jdk.java.net/.

**Comment by bennetelli** [comment]
@aahlenst We got it. There is a problem with the rxvt-unicode terminal. Seems like rxvt-unicode and jshell don't work nicely together. Using gnome-terminal works as expected.

**Comment by aahlenst** [comment]
If it happens with a build from jdk.java.net, it might make sense to report it to https://bugreport.java.com/bugreport/ by **only mentioning the build from jdk.java.net**. Please post a link here once the report was processed.

**Comment by karianna** [comment]
@bennetelli Are you able to try with the latest 17.0.3?

**Comment by bennetelli** [comment]
you were faster than me. Thanks for taking a look at it :)
