### ISSUE TITLE
AdoptOpenJDK 11 32-bit vs 64-bit discrepancy in java.net module

### ISSUE THREAD

**Issue by japievdlinde** [adoptium/adoptium-support#296]
An issue occurs when using AdoptOpenJDK 11.0.11 32-bit while attempting to make a connection to the SQL Server database using JDBC (JDBC driver being the Microsoft JDBC Driver 8.2 for SQL Server (mssql-jdbc-8.2.2.jre11.jar). This issue does not occur with the 64-bit build of AdoptOpenJDK 11.

Could you please help me understand what is different between the 32-bit and 64-bit JRE's?

**Java version output:**
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK Client VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Exception**
2021-04-22 11:39:37.501: An exception occurred: 
java.lang.ExceptionInInitializerError
	at java.base/java.net.Socket.setImpl(Socket.java:523)
	at java.base/java.net.Socket.<init>(Socket.java:88)
	at com.microsoft.sqlserver.jdbc.SocketFinder.getConnectedSocket(IOBuffer.java:2624)
	at com.microsoft.sqlserver.jdbc.SocketFinder.getDefaultSocket(IOBuffer.java:2611)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2338)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:659)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2546)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2216)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2067)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1204)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:825)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at postilion.esocketpos.upgrade.standard.sql.DatabaseUpgrader.getConnection(DatabaseUpgrader.java:659)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.base/java.net.AbstractPlainSocketImpl$1.run(AbstractPlainSocketImpl.java:84)
	at java.base/java.net.AbstractPlainSocketImpl$1.run(AbstractPlainSocketImpl.java:82)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.<clinit>(AbstractPlainSocketImpl.java:81)
	... 24 more

**Comment by nadzkie0** [comment]
https://github.com/adoptium/adoptium-support/issues/296#issue-864767734

**Comment by karianna** [comment]
My understanding is that the JDBC Driver is supported in 64 bit only (and expects to make 64-bit address calls?).
