### ISSUE TITLE
NPE at sun.awt.FcFontManager.getDefaultPlatformFont(FcFontManager.java:76) with java .282

### ISSUE THREAD

**Issue by k7295** [adoptium/adoptium-support#299]
I am getting this NPE on my Fedora 32 **docker** environment. It already has fontconfig installed and a fontconfig.properties on $JAVA_HOME/jre/lib.
* I builded my own binaries from hg.openjdk.java.net/jdk8u
* It was working before with java .252

```
Apr 29, 2021 12:31:29 AM sun.awt.X11FontManager registerFontDir
INFO: ParseFontDir /opt/openjdk-devel/jre/lib/fonts
Apr 29, 2021 12:31:29 AM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Apr 29, 2021 12:31:29 AM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for sans:regular:roman
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for sans:bold:roman
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for sans:regular:italic
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for sans:bold:italic
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for serif:regular:roman
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for serif:bold:roman
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for serif:regular:italic
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for serif:bold:italic
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for monospace:regular:roman
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for monospace:bold:roman
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for monospace:regular:italic
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for monospace:bold:italic
Apr 29, 2021 12:31:29 AM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no fonts at all.
Apr 29, 2021 12:31:29 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
Apr 29, 2021 12:31:29 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
Apr 29, 2021 12:31:30 AM sun.awt.X11FontManager registerFontDir
INFO: ParseFontDir /opt/openjdk-devel/jre/lib/fonts
Apr 29, 2021 12:31:30 AM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Apr 29, 2021 12:31:30 AM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Apr 29, 2021 12:31:30 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
Apr 29, 2021 12:31:30 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
Apr 29, 2021 12:31:30 AM sun.awt.X11FontManager registerFontDir
INFO: ParseFontDir /opt/openjdk-devel/jre/lib/fonts
Apr 29, 2021 12:31:30 AM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Apr 29, 2021 12:31:30 AM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Apr 29, 2021 12:31:30 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
Apr 29, 2021 12:31:30 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig

Caused by: java.lang.NullPointerException
        at sun.awt.FcFontManager.getDefaultPlatformFont(FcFontManager.java:76)
        at sun.font.SunFontManager$2.run(SunFontManager.java:443)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:386)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.awt.Font.getFont2D(Font.java:491)
        at java.awt.Font.canDisplay(Font.java:1984)
        at com.octo.captcha.component.image.fontgenerator.RandomFontGenerator.checkFontCanDisplayCharacters(RandomFontGenerator.java:223)
        at com.octo.captcha.component.image.fontgenerator.RandomFontGenerator.cleanFontList(RandomFontGenerator.java:179)
        at com.octo.captcha.component.image.fontgenerator.RandomFontGenerator.initializeFonts(RandomFontGenerator.java:94)
        at com.octo.captcha.component.image.fontgenerator.RandomFontGenerator.<init>(RandomFontGenerator.java:81)
        at rss.service.CaptchaService$RssGimpyEngine.buildInitialFactories(CaptchaService.java:135)
        at com.octo.captcha.engine.image.ListImageCaptchaEngine.<init>(ListImageCaptchaEngine.java:24)
        at com.octo.captcha.engine.image.gimpy.GmailEngine.<init>(GmailEngine.java:49)
        at com.octo.captcha.engine.image.gimpy.DefaultGimpyEngine.<init>(DefaultGimpyEngine.java:50)
        at rss.service.CaptchaService$RssGimpyEngine.<init>(CaptchaService.java:112)
        at rss.service.CaptchaService$RssGimpyEngine.<init>(CaptchaService.java:112)
        at rss.service.CaptchaService.<init>(CaptchaService.java:55)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.mockito.internal.util.reflection.ReflectionMemberAccessor.lambda$newInstance$0(ReflectionMemberAccessor.java:26)
        at org.mockito.internal.util.reflection.ReflectionMemberAccessor.newInstance(ReflectionMemberAccessor.java:26)
        at org.mockito.internal.util.reflection.ReflectionMemberAccessor.newInstance(ReflectionMemberAccessor.java:17)
        at org.mockito.internal.util.reflection.FieldInitializer$NoArgConstructorInstantiator.instantiate(FieldInitializer.java:202)
        at org.mockito.internal.util.reflection.FieldInitializer.acquireFieldInstance(FieldInitializer.java:146)
        at org.mockito.internal.util.reflection.FieldInitializer.initialize(FieldInitializer.java:91)
        at org.mockito.internal.configuration.injection.PropertyAndSetterInjection.initializeInjectMocksField(PropertyAndSetterInjection.java:99)
        at org.mockito.internal.configuration.injection.PropertyAndSetterInjection.processInjection(PropertyAndSetterInjection.java:80)
        at org.mockito.internal.configuration.injection.MockInjectionStrategy.process(MockInjectionStrategy.java:67)
        at org.mockito.internal.configuration.injection.MockInjectionStrategy.relayProcessToNextStrategy(MockInjectionStrategy.java:90)
        at org.mockito.internal.configuration.injection.MockInjectionStrategy.process(MockInjectionStrategy.java:70)
        at org.mockito.internal.configuration.injection.MockInjectionStrategy.relayProcessToNextStrategy(MockInjectionStrategy.java:90)
        at org.mockito.internal.configuration.injection.MockInjectionStrategy.process(MockInjectionStrategy.java:70)
        at org.mockito.internal.configuration.injection.MockInjection$OngoingMockInjection.apply(MockInjection.java:91)
        at org.mockito.internal.configuration.DefaultInjectionEngine.injectMocksOnFields(DefaultInjectionEngine.java:26)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.injectCloseableMocks(InjectingAnnotationEngine.java:118)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.processInjectMocks(InjectingAnnotationEngine.java:61)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:48)
        at org.mockito.MockitoAnnotations.openMocks(MockitoAnnotations.java:82)
        ... 40 more
```

Anyone know what might be happening?

**Comment by jerboaa** [comment]
This seems to be the clue:

```
INFO: Fontconfig returned no fonts at all.
Apr 29, 2021 12:31:29 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
Apr 29, 2021 12:31:29 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
```

So it depends what `fontconfig.properties` contains and which fonts you've got installed.

**Comment by k7295** [comment]
just this 
```
[root@ff1d96bde93f code]# cat /opt/securelink/openjdk-devel/jre/lib/fontconfig.properties 
version=1
sequence.allfonts=default
```
But the thing is, I have never needed this file until now, if I use my old Java (.252) it works without that file. It also happens to me that if I delete the libfreetype file from this java (.282) and even without that fontconfig file the tests pass

**Comment by karianna** [comment]
@k7295 IIRC we changed the policy on bundling a default with Java and relying on the user's choice in their Linux O/S
