### ISSUE TITLE
NullPointerException in java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646)

### ISSUE THREAD

**Issue by funnelspider** [adoptium/adoptium-support#313]
Using my application with tomcat and java 11 fails
Tomcat uses a 2way gzip filter (GZIP2WayFilter https://www.predic8.com/gzip-compression-filter.htm)

When the jdk zip library is loaded, the exception occurs (at java.base/java.util.zip.ZipUtils.loadLibrary(ZipUtils.java:298))
Environment:
Using CATALINA_BASE:   "c:\workspace\tomcatJava11"
Using CATALINA_HOME:   "c:\workspace\tomcatJava11"
Using CATALINA_TMPDIR: "c:\workspace\tomcatJava11\temp"
Using JRE_HOME:        "C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot"
Using CLASSPATH:       "c:\workspace\tomcatJava11\bin\bootstrap.jar;c:\workspace\tomcatJava11\bin\tomcat-juli.jar"
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Server version: Apache Tomcat/9.0.37
Server built:   Jun 30 2020 20:09:49 UTC
Server number:  9.0.37.0
OS Name:        Windows 10
OS Version:     10.0
Architecture:   amd64
JVM Version:    11.0.11+9
JVM Vendor:     AdoptOpenJDK

Stacktrace: 
java.lang.NullPointerException
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at java.base/java.util.zip.ZipUtils.loadLibrary(ZipUtils.java:298)
        at java.base/java.util.zip.Deflater.<clinit>(Deflater.java:193)
        at java.base/java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:91)
        at java.base/java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:110)
        at com.osmoticweb.gzipfilter.GZIP2WayResponseStream.<init>(GZIP2WayResponseStream.java:25)
        at com.osmoticweb.gzipfilter.GZIP2WayResponseWrapper.getOutputStream(GZIP2WayResponseWrapper.java:31)
        at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:105)
        at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:105)
        at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:105)
        at org.springframework.security.web.util.OnCommittedResponseWrapper.getOutputStream(OnCommittedResponseWrapper.java:145)

After this,  a series of NoClassDefFoundErrors occur:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.util.zip.Deflater
        at java.base/java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:91)
        at java.base/java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:110)
        at com.osmoticweb.gzipfilter.GZIP2WayResponseStream.<init>(GZIP2WayResponseStream.java:25)
        at com.osmoticweb.gzipfilter.GZIP2WayResponseWrapper.getOutputStream(GZIP2WayResponseWrapper.java:31)
        at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:105)
        at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:105)
        at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:105)
        at org.springframework.security.web.util.OnCommittedResponseWrapper.getOutputStream(OnCommittedResponseWrapper.java:145)
        at org.springframework.http.server.ServletServerHttpResponse.getBody(ServletServerHttpResponse.java:97)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:422)
        at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:181)
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)

The same setup works if using AdoptOpenJdk 15 or 16 and it works using openjdk 11 
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

As I see it, the issue is within AdoptOpenJdk 11 itself.

**Comment by karianna** [comment]
@funnelspider - Can you try with an OpenJDK build at the same level?  You can try:

https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_11.0.11_9.zip

**Comment by funnelspider** [comment]
Seems to be the same issue.
I used the latest AdoptOpenJDK version at gave this error. Then I downloaded the latest OpenJDK and it worked. 
What is the issue then ?

**Comment by mikaelmechoulam** [comment]
Hello, one of the clients of our product seems to encounter a similar stack : 
Could not initialize class java.util.zip.Deflater
java.lang.NoClassDefFoundError: Could not initialize class java.util.zip.Deflater
	at java.util.zip.ZipOutputStream.<init>(ZipOutputStream.java:134) ~[?:?]
	at java.util.zip.ZipOutputStream.<init>(ZipOutputStream.java:120) ~[?:?]

Can it come from our application or could it be linked to this issue ? The version of JDK used is "openjdk version "11.0.14" 2022-01-18 LTS "

**Comment by karianna** [comment]
Please try with the latest 11.0.14.1 from adoptium.net and see if there's still an issue.

**Comment by jerboaa** [comment]
It's unlikely it will make a difference. The `11.0.14.1` patch release (from `11.0.14+9` January 2022 CPU) only contained changes mentioned here:
https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2022-February/012348.html

**Comment by mikaelmechoulam** [comment]
For your information, the client re-installed the same version of the JDK and it solved the issue. Interesting to see such an error can occur...

**Comment by funnelspider** [comment]
Why is this closed?
There is no apparent fix to why this happened in the first place.
This means it could be an issue any time

**Comment by karianna** [comment]
@funnelspider - @mikaelmechoulam reported that a JVM reinstall fixed their issue - can you also try?

**Comment by funnelspider** [comment]
I wasn't installing it. I was unzipping it.
I did that several times and it reproduced each time.

Can't you reproduce it ?

**Comment by karianna** [comment]
@funnelspider I'm not able to reproduce this using the latest 11.0.16.1 - can you try installing that version and send us the updated log if it crashes/fails?

**Comment by funnelspider** [comment]
I don't have the project anymore and it was working fine with java 17
No idea what was wrong with java 11 but it's of little interest right now. 

You may close it
