### ISSUE TITLE
java.awt.image.RasterFormatException: (y + height) is outside raster

### ISSUE THREAD

**Issue by bhaveshkharwa** [adoptium/adoptium-support#321]
I am using AdoptOpenJDK version jdk8u292-b10.  Getting following error while generating preview using PDF file.

`Unable to generate rendition : : java.awt.image.RasterFormatException: (y + height) is outside raster
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:470)
	at sun.awt.image.IntegerInterleavedRaster.createChild(IntegerInterleavedRaster.java:514)
	at sun.java2d.pipe.GeneralCompositePipe.renderPathTile(GeneralCompositePipe.java:106)
	at sun.java2d.pipe.AAShapePipe.renderTiles(AAShapePipe.java:202)
	at sun.java2d.pipe.AAShapePipe.renderPath(AAShapePipe.java:150)
	at sun.java2d.pipe.AAShapePipe.fill(AAShapePipe.java:83)
	at sun.java2d.pipe.PixelToParallelogramConverter.fill(PixelToParallelogramConverter.java:164)
	at sun.java2d.pipe.ValidatePipe.fill(ValidatePipe.java:160)
	at sun.java2d.SunGraphics2D.fill(SunGraphics2D.java:2527)
	at org.apache.pdfbox.rendering.PageDrawer.shadingFill(PageDrawer.java:1146)`

**Comment by karianna** [comment]
https://stackoverflow.com/questions/56907643/selenium-java-awt-image-rasterformatexception-y-height-is-outside-of-raste

**Comment by bhaveshkharwa** [comment]
I am using following code to generate Image based on PDF file.
`import java.awt.image.BufferedImage;
import java.io.IOException;

import org.apache.log4j.Logger;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;



import net.coobird.thumbnailator.Thumbnails;

public class PdfRenditionGenerator {

	private static final Logger LOG = LoggerFactory.getLogger();

	public byte[] generateRendition(byte[] imageBytes, String mimeType, Rendition rendition)
			throws IOException, UnsupportedOutputFormatException {
		byte[] outputBytes = null;
		try {
			try (final PDDocument pdf = PDDocument.load(imageBytes)) {

				if (pdf != null && pdf.getNumberOfPages() > 0) {
					PDFRenderer renderer = new PDFRenderer(pdf);
					BufferedImage image = renderer.renderImage(0, 1);
					final BufferedImage scaledImage;
					if (image.getWidth() > 500) {
						scaledImage = Thumbnails.of(image).width(rendition.getWidth()).asBufferedImage();
					} else {
						scaledImage = image;
					}
					outputBytes = //write bufferedimage to bytes

				}
			}
		} catch (Exception e) {
			e.printStackTrace();			
		} 
		return outputBytes;
	}
}`

The following line throw java.awt.image.RasterFormatException: (y + height) is outside raster

BufferedImage image = renderer.renderImage(0, 1);
