### ISSUE TITLE
java.imageio throws exception on large tiff file.

### ISSUE THREAD

**Issue by tbdasap** [adoptium/adoptium-support#325]
Tested with JDK15. This is a JDK problem (and not just about openjdk).

## Summary
The standard TIFF plugin for "javax.imageio" throws an exception on a large CMYK tiff file.
The root cause is  [here at line 326](https://github.com/openjdk/jdk16/blob/master/src/java.desktop/share/classes/com/sun/imageio/plugins/tiff/TIFFIFD.java#L323-L330) wherein the code should be
```
stream.readFully(unit, 0, sz);
```
as the bytearray has just been allocated and it should be filled from position 0
as indicated by the documentation for [stream.readfully](https://docs.oracle.com/en/java/javase/16/docs/api/java.desktop/javax/imageio/stream/ImageInputStream.html#readFully(byte%5B%5D,int,int))

## Steps to reproduce

- Unzip the attached [testImageIO.zip](https://github.com/adoptium/adoptium-support/files/6833966/testImageIO.zip) into subdirectory `testImageIO`
- Set your JAVA_HOME. `export JAVA_HOME=Your_JDKinstallation`
- Run the testcase. `cd testimageio; ./test.sh`

[testImageIO.zip](https://github.com/adoptium/adoptium-support/files/6833966/testImageIO.zip)

## Expected results
This works with **JDK11.0.7** as below

```
$ cd testImageIO
$ java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
$ java ./testImageIO.java
#### IMAGIO: DEBUGGING #######
1  Standard GIF image reader
2  Standard BMP Image Reader
3  Standard WBMP Image Reader
4  Standard PNG image reader
5  Standard JPEG Image Reader
6  Standard TIFF image reader
#### END DEBUG: IMAGIO #######
Read: SUCCESS
```

## Actual results

Does not work with **JDK 11.0.8** and beyond
```
$ cd testImageIO
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
[testimageio@b93e34df603d] 02:12:27 ~/testImageIO [] $
java ./testImageIO.java
#### IMAGIO: DEBUGGING #######
1  Standard TIFF image reader
2  Standard PNG image reader
3  Standard GIF image reader
4  Standard BMP Image Reader
5  Standard WBMP Image Reader
6  Standard JPEG Image Reader
#### END DEBUG: IMAGIO #######
Read: FAILED
java.lang.IndexOutOfBoundsException: off < 0 || len < 0 || off + len > b.length!
        at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:346)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFIFD.readFieldValue(TIFFIFD.java:326)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFIFD.initialize(TIFFIFD.java:1088)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageMetadata.initializeFromStream(TIFFImageMetadata.java:88)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.readMetadata(TIFFImageReader.java:319)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.seekToImage(TIFFImageReader.java:291)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.prepareRead(TIFFImageReader.java:964)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1140)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
        at testImageIO.main(testImageIO.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119) 

```

## Triaging info

Java version:
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```

What is your operating system and platform?
RHEL7

How did you install Java?
RPM

Did it work before?
Works on 11.0.7 but not from 11.0.8 onwards. 
Does not work on JDK 15 or 16.

Did you test with other Java versions?
Yes. See above.

**Comment by jerboaa** [comment]
Reported upstream as: https://bugs.openjdk.java.net/browse/JDK-8270893

**Comment by karianna** [comment]
Fixed in latest 17 and 11
