### ISSUE TITLE
JLink images have broken https support

### ISSUE THREAD

**Issue by XakepSDK** [adoptium/adoptium-support#397]
## Summary
This error does not happen with all URLs. Only happens in JLink images.
This URL is affected: `https://launchermeta.mojang.com/v1/packages/fd990561a3502903a819815ca63b7ac13110a84c/21w44a.json`

## Steps to reproduce
1. Clone this: https://github.com/XakepSDK/jlink-bug
2. Run `mvn package` in root
3. Unpack package from `target/test-load-1.0-SNAPSHOT.zip`
4. Run `bin/launcher`

## Expected results
It works

## Actual results
It does not work
```
Exception in thread "main" javax.net.ssl.SSLProtocolException: Received close_notify during handshake
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:250)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:203)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1161)
        at test.load/dk.xakeps.testload.Main.main(Main.java:10)
```

## Triaging info

Java version:
On windows 10 amd64:
```
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM (build 17.0.1+12-LTS, mixed mode)
```
On Arch Linux:
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12)
OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)
```

What is your operating system and platform?
Windows, Arch Linux

How did you install Java?
1. Temurin installer on windows
2. Form Arch repos on Linux

Did it work before?
I don't know

Did you test with other Java versions?
No

**Comment by XakepSDK** [comment]
Fixed it. If anybody encounters it, add module `jdk.crypto.ec`. It can't find right crypto algorithms.

**Comment by sxa** [comment]
A quick note on this - the [blog entry about creating your own jlinked runtime](https://blog.adoptium.net/2021/10/jlink-to-produce-own-runtime/) explicitly mentions that the `jdk.crypto.ec` doesn't get picked up properly with `jdeps`, so it's not just you who has encountered this :-)

**Comment by tresf** [comment]
Adding for Google-Fu:

```
BCXDHPublicKey cannot be cast to class XECPublicKey
```

... same cause, different error. 🍻
