### ISSUE TITLE
FTP Explicit PROT P communication for zero byte file not working

### ISSUE THREAD

**Issue by deepanshujangid** [adoptium/adoptium-support#414]
I am trying to perform a FTP transfer for a file using FTP Explicit PROT P communication. It is working fine with non-zero byte file but with zero byte (blank) file, it is giving me below error -  

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at securelink.ftp.server.FTPDConnection.buildDataConnection(FTPDConnection.java:374)
        at securelink.ftp.server.FTPDConnection.storInternal(FTPDConnection.java:1313)
        at securelink.ftp.server.FTPDConnection.STOR(FTPDConnection.java:1265)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at securelink.ftp.server.FTPDConnection.run(FTPDConnection.java:675)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        ... 12 more

This error is occurring when the FTP client is sending STOR command to server and the server starts the the data binding. After I checked the code as per the trace starting from startHandshake() method, I reached to the decode() method in class SSLSocketInputRecord.java, where the below code is written -

int really = read(is, temporary, 0, headerSize);
            if (really < 0) {
                throw new EOFException("SSL peer shut down incorrectly");
            }

Since the file size is zero, it is throwing the exception.

So is this the actual behavior or this is a bug that will be resolved or has been resolved ?

If it has been resolved, please specify the version.

**Comment by karianna** [comment]
Which Java are you using? (java --version)

**Comment by deepanshujangid** [comment]
I am using Java 11. I tried with java 8 also, but the issue is same in that one.

**Comment by karianna** [comment]
are you using SFTP or FTPS?

**Comment by deepanshujangid** [comment]
Using FTPS.

**Comment by karianna** [comment]
I'd recommend trying Apache Commons Net (which does handle 0 byte files OK) https://commons.apache.org/proper/commons-net/

**Comment by deepanshujangid** [comment]
That might require a lot of changes in the code itself. Is there any other work around or any possibility that it might be handled in the future java release ?

**Comment by karianna** [comment]
> That might require a lot of changes in the code itself. Is there any other work around or any possibility that it might be handled in the future java release ?

I'm not sure if it a core Java issue to be fixed.  This would require a lot of discussion upstream at the OpenJDK project (openjdk.java.net)
