### ISSUE TITLE
failed to run HECHMS

### ISSUE THREAD

**Issue by ywang910516** [adoptium/adoptium-support#450]
I am using Ubuntu 16.04.7 LTS and the kernel version is 4.8.0-58-generic. I just followed the installation instruction like unzip using "tar" and run ./hec-hms.sh. Following is what I got. What should I do to solve this problem? Thanks for your attention.

```
==============================================================================
/volume/NFS/yw922/HEC-HMS-4.9/bin/taudem:/volume/NFS/yw922/HEC-HMS-4.9/bin/mpi:/volume/NFS/yw922/bin:/volume/NFS/yw922/miniconda3/bin:/volume/NFS/yw922/miniconda3/condabin:/usr/local/pandaseq-2.11/bin:/usr/local/Matlab2020a/bin:/usr/local/Python37/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/slurm/bin:/usr/local/cuda-9.1/bin
Native library load failed.
java.lang.UnsatisfiedLinkError: /volume/NFS/yw922/HEC-HMS-4.9/bin/gdal/libgdalalljni.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /volume/NFS/yw922/HEC-HMS-4.9/bin/gdal/./libgdal.so.26)
Feb 10, 2022 2:09:45 PM hms.m <init>
SEVERE: 'void org.gdal.gdal.gdalJNI.SetConfigOption(java.lang.String, java.lang.String)'
java.lang.UnsatisfiedLinkError: 'void org.gdal.gdal.gdalJNI.SetConfigOption(java.lang.String, java.lang.String)'
        at org.gdal.gdal.gdalJNI.SetConfigOption(Native Method)
        at org.gdal.gdal.gdal.SetConfigOption(gdal.java:180)
        at hms.m.<init>(Unknown Source)
        at hms.m.<clinit>(Unknown Source)
        at hms.Hms.<clinit>(Unknown Source)

Heclib.init: :java.lang.UnsatisfiedLinkError: /volume/NFS/yw922/HEC-HMS-4.9/bin/libjavaHeclib.so: libgfortran.so.5: cannot open shared object file: No such file or directory
Heclib.init:java library path=/volume/NFS/yw922/HEC-HMS-4.9/bin:/volume/NFS/yw922/HEC-HMS-4.9/bin/gdal
java.lang.UnsatisfiedLinkError: /volume/NFS/yw922/HEC-HMS-4.9/bin/libjavaHeclib.so: libgfortran.so.5: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at hec.heclib.util.Heclib.<clinit>(Heclib.java:195)
        at hec.heclib.dss.HecDSSFileAccess.zset(HecDSSFileAccess.java:308)
        at hms.model.ProjectManager.<init>(Unknown Source)
        at hms.Hms.<init>(Unknown Source)
        at hms.Hms.main(Unknown Source)
Exception in thread "main" java.lang.UnsatisfiedLinkError: /volume/NFS/yw922/HEC-HMS-4.9/bin/libjavaHeclib.so: libgfortran.so.5: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at hec.heclib.util.Heclib.<clinit>(Heclib.java:195)
        at hec.heclib.dss.HecDSSFileAccess.zset(HecDSSFileAccess.java:308)
        at hms.model.ProjectManager.<init>(Unknown Source)
        at hms.Hms.<init>(Unknown Source)
        at hms.Hms.main(Unknown Source)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3fe89a178c, pid=49376, tid=49419
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.9+11) (build 11.0.9+11)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.9+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0xc78c]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /volume/NFS/yw922/HEC-HMS-4.9/hs_err_pid49376.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./hec-hms.sh: line 38: 49376 Aborted                 $JAVA_EXE -DMapPanel.NoVolatileImage=true -Xms32M $PYOPTS $JAVA_LIB_OPT -classpath $DIR/*:$DIR/ui:$DIR/lib/*:$DIR/lib/hec/* $PROG $*
============================================================================
```

**Comment by karianna** [comment]
Can you try 11.0.14 from adoptium.net and see if that works?

**Comment by ywang910516** [comment]
Sorry that I cannot change the system since I am using HPC organized by the
department. Do you have any idea about what caused this problem? Thank you!

Best
Yifan

Martijn Verburg ***@***.***> 于2022年2月10日周四 16:16写道：

**Comment by smlambert** [comment]
Have you confirmed the existence of libgfortran.so.5, as the error is saying that there is an attempt to open it but cannot find it.  

`/volume/NFS/yw922/HEC-HMS-4.9/bin/libjavaHeclib.so: libgfortran.so.5: cannot open shared object file: No such file or directory`

Potentially related: 
https://stackoverflow.com/questions/59182655/why-libgfortran-so-5-is-not-located-after-upgrade-to-the-newest-gcc
https://stackoverflow.com/questions/56932991/how-to-fix-importerror-libgfortran-so-5-cannot-open-shared-object-file-no-su
