### ISSUE TITLE
Upgrade zlib in Alpine Docker images (and maybe others as well)

### ISSUE THREAD

**Issue by Marcono1234** [adoptium/adoptium-support#499]
## Summary

It appears there was a behavior change in zlib 1.2.12 which broke the Java classes `ZipInputStream` and `GZIPInputStream`, causing them to erroneously fail with:
- `ZipException: invalid entry CRC`
- `ZipException: Corrupt GZIP trailer`

See https://github.com/madler/zlib/issues/618 and [JDK-8286174](https://bugs.openjdk.java.net/browse/JDK-8286174).

In the Alpine Temurin Docker images affected by this issue the installed zlib version appears to be 1.2.12-r0, but an update 1.2.12-r1 is available which seems to fix this issue.

## Steps to reproduce
With a recent Temurin Alpine image (such as `eclipse-temurin:18.0.1_10-jdk-alpine`), perform the reproduction steps described in [JDK-8286174](https://bugs.openjdk.java.net/browse/JDK-8286174). Note that the `sha256sum` commands shown there are broken because apparently the two spaces between hash and file name were converted to a single space.

## Expected results

`ZipInputStream` and `GZIPInputStream` should work correctly.

## Actual results

`ZipInputStream` and `GZIPInputStream` fail to read valid files.

## Triaging info

Java version:
```
openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode, sharing)
```

What is your operating system and platform?
How did you install Java?
> Docker image `eclipse-temurin:18.0.1_10-jdk-alpine`

Did it work before?
> Yes, in older images such as `eclipse-temurin:11.0.13_8-jdk-alpine` which seem to have a zlib version < 1.2.12 installed (e.g. zlib-1.2.11-r3).

**Comment by gdams** [comment]
I assume that this would need a manual rebuild of the images to pick up the newer zlip dependency? CC @yosifkit/@tianon to see if that's something that can be done

**Comment by Marcono1234** [comment]
Might also be good if you could verify that this is indeed an issue. For me this problem occurred consistently with Docker, but in JDK-8286174 one of the Oracle employees commented that they were not able to reproduce the issue. They were using Podman instead of Docker, and that was for the `openjdk` image, but I would have expected that this should not make a difference.

**Comment by sxa** [comment]
Hmmm I can't reproduce this - running the test in that bug report with jshell doesn't seem to cause the error described (tested with podman on Fedora, then verified with 'real' docker on Ubuntu 20.04) The version of zlib was `1.2.12-r0` in both cases:

`in ==> java.util.zip.ZipInputStream@cc34f4d`

`in ==> java.util.zip.GZIPInputStream@50040f0c`

**Comment by Nyamiou** [comment]
I think we are also facing this issue using the "eclipse-temurin:11-jdk-alpine" image. Here is an extract of the stacktrace we are getting (using RDF4J and Apache HttpClient to call a GraphDB database):

`Caused by: java.util.zip.ZipException: Corrupt GZIP trailer
	at java.base/java.util.zip.GZIPInputStream.readTrailer(GZIPInputStream.java:226)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:120)
	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:70)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:164)
	at java.base/java.io.FilterReader.read(FilterReader.java:65)
	at java.base/java.io.PushbackReader.read(PushbackReader.java:90)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.readCodePoint(TurtleParser.java:1217)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.skipWSC(TurtleParser.java:1170)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:163)
	at org.eclipse.rdf4j.query.impl.BackgroundGraphResult.run(BackgroundGraphResult.java:88)
	at org.eclipse.rdf4j.http.client.BackgroundResultExecutor.lambda$autoCloseRunnable$0(BackgroundResultExecutor.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 common frames omitted`

I've been debugging this issue on our Docker image for a few days that is impossible to reproduce locally on our work (Windows) computers until I found the mentioned JDK issue. And going back to "eclipse-temurin:11.0.13_8-jdk-alpine" does fix the issue.

We are probably going to use the older version for our next release in the meantime but we are really looking forward for this fix.

**Comment by Marcono1234** [comment]
> Hmmm I can't reproduce this - running the test in that bug report with jshell doesn't seem to cause the error described (tested with podman on Fedora, then verified with 'real' docker on Ubuntu 20.04)

Could this be CPU specific? To me it looks like zlib's [`crc32.c`](https://github.com/madler/zlib/blob/master/crc32.c) contains code specific to certain CPU features, but I am not very familiar with C.
The device where I can consistently reproduce this issue uses AMD Phenom II X6 1055T. However, on other device also with Windows 10 as OS but with a different CPU I cannot reproduce it either.

**Comment by gdams** [comment]
@Marcono1234 can you confirm if this is fixed in `eclipse-temurin:18-jdk-alpine` now?

**Comment by Marcono1234** [comment]
Tried it now with `eclipse-temurin:18-jdk-alpine` (`eclipse-temurin@sha256:44e422ec2058b9003e8f55093930b033b28f6a297201dcdd70ec3b79983d21a9`) and the issue seems to be fixed. That image contains `zlib-1.2.12-r1` which is apparently not affected by this issue.

But might be good if @Nyamiou could give it a try as well since they were experiencing the issue too.

**Comment by gdams** [comment]
I'm going to close for now as the `zlib` version has been updated. Feel free to re-open if this is still causing issues

**Comment by mqu** [comment]
we are having [same trouble with SonarQube](https://github.com/SonarSource/docker-sonarqube/issues/544#issuecomment-1203934447) ; this is related to CPU flags under virtualized environment. Seems not related with Docker.

For me, last alpine release did not solved this issue.

To reproduce : 
- open a shell on a virtual environment, with CPU := host (Intel, AMD),
- install docker
- run : `docker run --rm -it sonarqube:9.5-community` and wait for elasticsearch exception checksum.

**Comment by Marcono1234** [comment]
@mqu, I am seeing this issue as well for `sonarqube:9.5-community`, but I think the reason is that they simply have not updated the base image yet. https://github.com/SonarSource/docker-sonarqube/issues/544#issuecomment-1199289967 says:

> Normally, this should have been fixed in 9.5. We were also waiting on Alpine to publish a new version of 3.15 which would include some other fixes we were waiting on. I'll update our base image today. This will be part of the upcoming 9.6 version.

That might be a bit confusingly worded, but I think the main point here is: "This will be part of the upcoming 9.6 version."
