### ISSUE TITLE
NullPointerException occurs when using Apache FOP 0.93 to render a GIF or PNG image into a PDF

### ISSUE THREAD

**Issue by tonedef71** [adoptium/adoptium-support#582]
### Please provide a brief summary of the bug

While running Apache FOP 0.93 to render a PDF from an XML schema which references an external GIF or PNG file, a `NullPointerException` is thrown when FOP attempts to render the image into the PDF document.  When a BMP or JPG image is referenced instead, the NPE does not get thrown.  Browsing through the FOP source code it appears likely that the ICC color space is not being properly obtained for PNG and GIF images (presumably images that support transparency).  The AWT portion of the Java runtime probably handles the ICC color processing.

This issue seems to be a Java compatibility issue for OpenJDK because the `NullPointerException` does not occur when the same code is run with the Oracle Java 8 runtime (tested with Oracle build 1.8.0_341).  

This issue has been verified on Windows 10 with two arbitrary versions of Temurin 8 version (jdk8u322-b06 and jdk8u345-b01).  The issue has also been verified to occur on RHE Linux 6 running the Azul/Zulu build of OpenJDK 8 (build 1.8.0_252-b14).

Perhaps the Oracle Java 8 builds package something differently from the various OpenJDK 8 builds?

I will attach a ZIP archive containing XSL/XML resources, shell scripts, and FOP libraries which can be used to reproduce the issue.

### Please provide steps to reproduce where possible

Unpack the `test_fop_with_openjdk8.zip` file into a test folder.

Modify the `JAVA_HOME` environment variable in the various shell script files as appropriate to point to the Java 8 runtime version to be tested.

Execute the `test_fop_openjdk8.bat` to reproduce the NPE in OpenJDK 8 on Windows.
Execute the `test_fop_openjdk8.sh` to reproduce the NPE in OpenJDK 8 on Linux.

Execute the `test_fop_oracle8.bat` to verify no NPE in Oracle Java 8 on Windows.
Execute the `test_fop_oracle8.sh` to verify no NPE in Oracle Java 8 on Linux.

The bundled `test.xsl` file defaults to testing with a JPG image.  There are other image types in that file which have been commented out but can alternatively be used as an external image for testing.

[test_fop_with_openjdk8.zip](https://github.com/adoptium/adoptium-support/files/9528513/test_fop_with_openjdk8.zip)

### Expected Results

When the `test_fop_openjdk8` script was run (with a PNG image embedded in the `text.xsl` schema file), I expected no errors to occur.

### Actual Results

When the `test_fop_openjdk8` script was run (with a PNG image embedded in the text.xsl schema file), a `NullPointerException` is thrown:
```
java.lang.NullPointerException
        at org.apache.fop.render.pdf.FopPDFImage.setup(FopPDFImage.java:144)
        at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:726)
        at org.apache.fop.render.pdf.PDFRenderer.putImage(PDFRenderer.java:1464)
        at org.apache.fop.render.pdf.PDFRenderer.renderImage(PDFRenderer.java:1391)
        at org.apache.fop.render.AbstractRenderer.renderViewport(AbstractRenderer.java:752)
        at org.apache.fop.render.AbstractPathOrientedRenderer.renderViewport(AbstractPathOrientedRenderer.java:541)
        at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:635)
        at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:610)
        at org.apache.fop.render.pdf.PDFRenderer.renderLineArea(PDFRenderer.java:1081)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:536)
        at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:586)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:526)
        at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:431)
        at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:410)
        at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:344)
        at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:289)
        at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:262)
        at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:236)
        at org.apache.fop.render.pdf.PDFRenderer.renderPage(PDFRenderer.java:713)
        at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:120)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:786)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:159)
        at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:385)
        at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:148)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:378)
        at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:194)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:263)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:557)
        at test.template$dot$0()
        at test.applyTemplates()
        at test.transform()
        at com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet.transform(AbstractTranslet.java:624)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:732)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:345)
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:165)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
        at org.apache.fop.cli.Main.startFOP(Main.java:160)
        at org.apache.fop.cli.Main.main(Main.java:191)
```
        
This NPE does not get thrown when the `test_fop_oracle8` script is run (with a PNG image embedded in the text.xsl schema file).

### What Java Version are you using?

openjdk version "1.8.0_345" OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01) OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)

### What is your operating system and platform?

Windows 10 Enterprise 20H2 build 19042.1889

Linux 2.6.32-754.35.1.el6.x86_64 #1 SMP Wed Sep 16 06:48:01 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

### How did you install Java?

Java 8 was installed on Windows by running an official installer executable, and it was installed on Linux via a package manager facility.

### Did it work before?

```shell
It always worked previously with Oracle Java runtimes.  The issue was first discovered after switching from an Oracle Java runtime to the Zulu/Azul OpenJDK 8 runtime.
```

### Did you test with other Java versions?

```shell
This one did not work:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-linux64) (build 1.8.0_252-b14)
OpenJDK 64-Bit Server VM (Zulu 8.46.0.19-CA-linux64) (build 25.252-b14, mixed mode)


This one did not work:
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)


This one did not work:
openjdk version "1.8.0_345" 
OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)


This one did actually work:
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)
```

### Relevant log output

```shell
C:\Stage\FOP_Testing\shell>"C:\jdk8u345-b01"\jre\bin\java -cp fop.jar;commons-logging-1.0.4.jar;avalon-framework-4.2.0.jar;xmlgraphics-commons-1.1.jar;batik-all-1.6.jar;commons-io-1.1.jar -jar fop.jar -xml test.xml -pdf test.pdf -xsl test.xsl
Sep 08, 2022 10:49:22 AM org.apache.fop.cli.InputHandler error
SEVERE: javax.xml.transform.TransformerException:
Sep 08, 2022 10:49:22 AM org.apache.fop.cli.Main startFOP
SEVERE: Exception
org.apache.fop.apps.FOPException: java.lang.NullPointerException
javax.xml.transform.TransformerException: java.lang.NullPointerException
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:168)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
        at org.apache.fop.cli.Main.startFOP(Main.java:160)
        at org.apache.fop.cli.Main.main(Main.java:191)
Caused by: javax.xml.transform.TransformerException: java.lang.NullPointerException
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:739)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:345)
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:165)
        ... 3 more
Caused by: java.lang.NullPointerException
        at org.apache.fop.render.pdf.FopPDFImage.setup(FopPDFImage.java:144)
        at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:726)
        at org.apache.fop.render.pdf.PDFRenderer.putImage(PDFRenderer.java:1464)
        at org.apache.fop.render.pdf.PDFRenderer.renderImage(PDFRenderer.java:1391)
        at org.apache.fop.render.AbstractRenderer.renderViewport(AbstractRenderer.java:752)
        at org.apache.fop.render.AbstractPathOrientedRenderer.renderViewport(AbstractPathOrientedRenderer.java:541)
        at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:635)
        at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:610)
        at org.apache.fop.render.pdf.PDFRenderer.renderLineArea(PDFRenderer.java:1081)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:536)
        at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:586)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:526)
        at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:431)
        at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:410)
        at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:344)
        at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:289)
        at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:262)
        at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:236)
        at org.apache.fop.render.pdf.PDFRenderer.renderPage(PDFRenderer.java:713)
        at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:120)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:786)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:159)
        at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:385)
        at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:148)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:378)
        at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:194)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:263)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:557)
        at test.template$dot$0()
        at test.applyTemplates()
        at test.transform()
        at com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet.transform(AbstractTranslet.java:624)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:732)
        ... 5 more

---------

javax.xml.transform.TransformerException: java.lang.NullPointerException
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:739)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:345)
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:165)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
        at org.apache.fop.cli.Main.startFOP(Main.java:160)
        at org.apache.fop.cli.Main.main(Main.java:191)
Caused by: java.lang.NullPointerException
        at org.apache.fop.render.pdf.FopPDFImage.setup(FopPDFImage.java:144)
        at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:726)
        at org.apache.fop.render.pdf.PDFRenderer.putImage(PDFRenderer.java:1464)
        at org.apache.fop.render.pdf.PDFRenderer.renderImage(PDFRenderer.java:1391)
        at org.apache.fop.render.AbstractRenderer.renderViewport(AbstractRenderer.java:752)
        at org.apache.fop.render.AbstractPathOrientedRenderer.renderViewport(AbstractPathOrientedRenderer.java:541)
        at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:635)
        at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:610)
        at org.apache.fop.render.pdf.PDFRenderer.renderLineArea(PDFRenderer.java:1081)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:536)
        at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:586)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:526)
        at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:431)
        at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:410)
        at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:344)
        at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:289)
        at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:262)
        at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:236)
        at org.apache.fop.render.pdf.PDFRenderer.renderPage(PDFRenderer.java:713)
        at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:120)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:786)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:159)
        at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:385)
        at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:148)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:378)
        at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:194)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:263)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:557)
        at test.template$dot$0()
        at test.applyTemplates()
        at test.transform()
        at com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet.transform(AbstractTranslet.java:624)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:732)
        ... 5 more
---------

C:\stage>"C:\jdk8u345-b01"\jre\bin\java -cp fop.jar;commons-logging-1.0.4.jar;avalon-framework-4.2.0.jar;xmlgraphics-commons-1.1.jar;batik-all-1.6.jar;commons-io-1.1.jar -jar fop.jar -xml test.xml -pdf test.pdf -xsl test.xsl
Sep 08, 2022 9:27:15 AM org.apache.fop.cli.InputHandler error
SEVERE: javax.xml.transform.TransformerException:
Sep 08, 2022 9:27:15 AM org.apache.fop.cli.Main startFOP
SEVERE: Exception
org.apache.fop.apps.FOPException: java.lang.NullPointerException
javax.xml.transform.TransformerException: java.lang.NullPointerException
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:168)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
        at org.apache.fop.cli.Main.startFOP(Main.java:160)
        at org.apache.fop.cli.Main.main(Main.java:191)
Caused by: javax.xml.transform.TransformerException: java.lang.NullPointerException
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:739)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:345)
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:165)
        ... 3 more
Caused by: java.lang.NullPointerException
        at org.apache.fop.render.pdf.FopPDFImage.setup(FopPDFImage.java:144)
        at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:726)
        at org.apache.fop.render.pdf.PDFRenderer.putImage(PDFRenderer.java:1464)
        at org.apache.fop.render.pdf.PDFRenderer.renderImage(PDFRenderer.java:1391)
        at org.apache.fop.render.AbstractRenderer.renderViewport(AbstractRenderer.java:752)
        at org.apache.fop.render.AbstractPathOrientedRenderer.renderViewport(AbstractPathOrientedRenderer.java:541)
        at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:635)
        at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:610)
        at org.apache.fop.render.pdf.PDFRenderer.renderLineArea(PDFRenderer.java:1081)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:536)
        at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:586)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:526)
        at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:431)
        at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:410)
        at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:344)
        at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:289)
        at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:262)
        at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:236)
        at org.apache.fop.render.pdf.PDFRenderer.renderPage(PDFRenderer.java:713)
        at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:120)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:786)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:159)
        at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:385)
        at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:148)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:378)
        at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:194)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:263)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:557)
        at test.template$dot$0()
        at test.applyTemplates()
        at test.transform()
        at com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet.transform(AbstractTranslet.java:624)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:732)
        ... 5 more

---------

javax.xml.transform.TransformerException: java.lang.NullPointerException
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:739)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:345)
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:165)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
        at org.apache.fop.cli.Main.startFOP(Main.java:160)
        at org.apache.fop.cli.Main.main(Main.java:191)
Caused by: java.lang.NullPointerException
        at org.apache.fop.render.pdf.FopPDFImage.setup(FopPDFImage.java:144)
        at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:726)
        at org.apache.fop.render.pdf.PDFRenderer.putImage(PDFRenderer.java:1464)
        at org.apache.fop.render.pdf.PDFRenderer.renderImage(PDFRenderer.java:1391)
        at org.apache.fop.render.AbstractRenderer.renderViewport(AbstractRenderer.java:752)
        at org.apache.fop.render.AbstractPathOrientedRenderer.renderViewport(AbstractPathOrientedRenderer.java:541)
        at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:635)
        at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:610)
        at org.apache.fop.render.pdf.PDFRenderer.renderLineArea(PDFRenderer.java:1081)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:536)
        at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:586)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:526)
        at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:431)
        at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:410)
        at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:344)
        at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:289)
        at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:262)
        at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:236)
        at org.apache.fop.render.pdf.PDFRenderer.renderPage(PDFRenderer.java:713)
        at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:120)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:786)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:159)
        at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:385)
        at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:148)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:378)
        at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:194)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:263)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:557)
        at test.template$dot$0()
        at test.applyTemplates()
        at test.transform()
        at com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet.transform(AbstractTranslet.java:624)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:732)
        ... 5 more
---------
java.lang.NullPointerException
        at org.apache.fop.render.pdf.FopPDFImage.setup(FopPDFImage.java:144)
        at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:726)
        at org.apache.fop.render.pdf.PDFRenderer.putImage(PDFRenderer.java:1464)
        at org.apache.fop.render.pdf.PDFRenderer.renderImage(PDFRenderer.java:1391)
        at org.apache.fop.render.AbstractRenderer.renderViewport(AbstractRenderer.java:752)
        at org.apache.fop.render.AbstractPathOrientedRenderer.renderViewport(AbstractPathOrientedRenderer.java:541)
        at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:635)
        at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:610)
        at org.apache.fop.render.pdf.PDFRenderer.renderLineArea(PDFRenderer.java:1081)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:536)
        at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:586)
        at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:526)
        at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:431)
        at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:410)
        at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:344)
        at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:289)
        at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:262)
        at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:236)
        at org.apache.fop.render.pdf.PDFRenderer.renderPage(PDFRenderer.java:713)
        at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:120)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:786)
        at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:159)
        at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:385)
        at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:148)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:378)
        at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:194)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:263)
        at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:557)
        at test.template$dot$0()
        at test.applyTemplates()
        at test.transform()
        at com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet.transform(AbstractTranslet.java:624)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:732)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:345)
        at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:165)
        at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:115)
        at org.apache.fop.cli.Main.startFOP(Main.java:160)
        at org.apache.fop.cli.Main.main(Main.java:191)
```

**Comment by karianna** [comment]
@tonedef71 Are you able to upgrade FOP to 0.95?  There's a number of historical bug reports for 0.93 and most users reported it fixed when upgrading.

**Comment by tonedef71** [comment]
> @tonedef71 Are you able to upgrade FOP to 0.95? There's a number of historical bug reports for 0.93 and most users reported it fixed when upgrading.

@karianna  I tested by swapping out to FOP 0.95, and while that particular NPE instance does stop occurring, FOP 0.95 requires its own particular versions of dependencies (e.g. `xmlgraphics-commons-1.3.1.jar`), and different errors began to occur in the actual JNLP-launched product we are running (which uses FOP to render its PDFs).  Unfortunately, I don't believe the vendor who supports the JNLP-launched product we are using will be open to certifying the product for FOP 0.95.

I would like to know why the NPE only occurs when running with OpenJDK 8 and not when running with Oracle Java 8.  I wonder if the Oracle Java 8 has the benefit of using some internal Sun Microsystems library which the OpenJDK 8 is not licensed to use.

**Comment by karianna** [comment]
That's correct, I'm afraid you'll need to persuade your vendor to allow the
upgrading of the stack.
Cheers,
Martijn
