### ISSUE TITLE
why throw UnsatisfiedLinkError

### ISSUE THREAD

**Issue by a364176773** [adoptium/adoptium-support#627]
kafka-clients 2.8.1
jdk 17.0.4
os alpine-linux 3.12.9 
```
Caused by: org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-9a71b682-edba-44ec-a57a-4a41de8ef6c3-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.7-9a71b682-edba-44ec-a57a-4a41de8ef6c3-libsnappyjava.so)
	at org.apache.kafka.common.record.CompressionType$3.wrapForInput(CompressionType.java:92)
	at org.apache.kafka.common.record.DefaultRecordBatch.compressedIterator(DefaultRecordBatch.java:261)
	at org.apache.kafka.common.record.DefaultRecordBatch.streamingIterator(DefaultRecordBatch.java:346)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1576)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1613)
	... 114 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-9a71b682-edba-44ec-a57a-4a41de8ef6c3-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.7-9a71b682-edba-44ec-a57a-4a41de8ef6c3-libsnappyjava.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:198)
	at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:167)
	at org.xerial.snappy.Snappy.init(Snappy.java:69)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:46)
	at org.xerial.snappy.SnappyInputStream.readFully(SnappyInputStream.java:145)
	at org.xerial.snappy.SnappyInputStream.readHeader(SnappyInputStream.java:99)
	at org.xerial.snappy.SnappyInputStream.<init>(SnappyInputStream.java:59)
	at org.apache.kafka.common.record.CompressionType$3.wrapForInput(CompressionType.java:90)
	... 118 common frames omitted
```

**Comment by karianna** [comment]
Can you try our latest 17.0.5 and post the result here?  I assume you're using the official Alpine images from DockerHub?

**Comment by a364176773** [comment]
> Can you try our latest 17.0.5 and post the result here? I assume you're using the official Alpine images from DockerHub?

We use the https://hub.docker.com/layers/library/alpine/3.12.9/images/sha256-45a18fc6f681b6bdfcd0cd37ab57384bb5ceb7aa300b0c981c9b676dba805120?context=explore 

I'll try to use 17.0.5 but not as soon, I'll reply as soon as I hear something, thanks for your support!

**Comment by a364176773** [comment]
> Can you try our latest 17.0.5 and post the result here? I assume you're using the official Alpine images from DockerHub?

The compression algorithm is fine when set to lz4, when using the snappy compression algorithm it will report an error

**Comment by a364176773** [comment]
@karianna Take a look the https://github.com/xerial/snappy-java/issues/181

**Comment by karianna** [comment]
Can you try https://hub.docker.com/_/eclipse-temurin/ with the eclipse-temurin:<version>-alpine variant.  That way you have a muslc based JVM on the latest Alpine image.

**Comment by a364176773** [comment]
> Can you try https://hub.docker.com/_/eclipse-temurin/ with the eclipse-temurin:-alpine variant. That way you have a muslc based JVM on the latest Alpine image.

i can try it,thx

**Comment by a364176773** [comment]
I tried the alpine image of eclipse-temurin and could not solve the problem, I solved it by installing the java-snappy-native package
```
2023-01-03 13:48:18.775 ERROR 148 --- [kafka-producer-network-thread | producer-1] o.apache.kafka.common.utils.KafkaThread  : Uncaught exception in thread 'kafka-producer-network-thread | producer-1':

java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.pure.UnsafeUtil
        at org.xerial.snappy.pure.SnappyRawCompressor.writeUncompressedLength(SnappyRawCompressor.java:405)
        at org.xerial.snappy.pure.SnappyRawCompressor.compress(SnappyRawCompressor.java:111)
        at org.xerial.snappy.pure.PureJavaSnappy.rawCompress(PureJavaSnappy.java:128)
        at org.xerial.snappy.Snappy.rawCompress(Snappy.java:450)
        at org.xerial.snappy.Snappy.compress(Snappy.java:123)
        at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:380)
        at org.xerial.snappy.SnappyOutputStream.flush(SnappyOutputStream.java:334)
        at org.xerial.snappy.SnappyOutputStream.close(SnappyOutputStream.java:419)
        at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:191)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.closeForRecordAppends(MemoryRecordsBuilder.java:281)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.close(MemoryRecordsBuilder.java:316)
        at org.apache.kafka.clients.producer.internals.ProducerBatch.close(ProducerBatch.java:410)
        at org.apache.kafka.clients.producer.internals.RecordAccumulator.drainBatchesForOneNode(RecordAccumulator.java:609)
        at org.apache.kafka.clients.producer.internals.RecordAccumulator.drain(RecordAccumulator.java:636)
        at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:360)
        at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:326)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:242)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: org.xerial.snappy.SnappyError: [UNSUPPORTED_PLATFORM] pure-java snappy requires access to java.nio.Buffer raw address field
                at org.xerial.snappy.pure.UnsafeUtil.<clinit>(UnsafeUtil.java:49)
                at org.xerial.snappy.pure.SnappyRawCompressor.writeUncompressedLength(SnappyRawCompressor.java:405)
                at org.xerial.snappy.pure.SnappyRawCompressor.compress(SnappyRawCompressor.java:111)
                at org.xerial.snappy.pure.PureJavaSnappy.rawCompress(PureJavaSnappy.java:128)
                at org.xerial.snappy.Snappy.rawCompress(Snappy.java:450)
                at org.xerial.snappy.Snappy.compress(Snappy.java:123)
                at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:380)
                at org.xerial.snappy.SnappyOutputStream.flush(SnappyOutputStream.java:334)
                at java.base/java.io.DataOutputStream.flush(DataOutputStream.java:128)
                at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
                ... 9 common frames omitted
```

**Comment by karianna** [comment]
@a364176773 Ah I see - specific Snappy support was required, thanks!
