### ISSUE TITLE
WTFCrash in libjfxwebkit.so

### ISSUE THREAD

**Issue by vlapra** [adoptium/adoptium-support#635]
### Please provide a brief summary of the bug

Application time to time crashed outside the Java Virtual Machine in native code.

### Please provide steps to reproduce where possible

We are not able to reproduce, but it happened several times on different computers.

Can someone tell us where the problem is?

### Expected Results

Not crash

### Actual Results

WTFCrash in libjfxwebkit.so

### What Java Version are you using?

# JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9) # Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)

### What is your operating system and platform?

Centos 7

### Relevant log output

```shell
Core was generated by `/usr/bin/java -Xms512m -Xmx6144m -Xlog:gc*:/home/ods/logs/gc.log:time,level,tag'.
Program terminated with signal 6, Aborted.
#0  0x00007ff4f55b83ce in raise () from /opt/glibc/glibc-2.14/libc.so.6
Missing separate debuginfos, use: debuginfo-install adoptopenjdk-11-hotspot-11.0.11+9-3.x86_64 atk-1.30.0-1.el6.x86_64 cairo-1.8.8-6.el6_6.x86_64 expat-2.0.1-11.el6_2.x86_64 fontconfig-2.8.0-5.el6.x86_64 freetype-2.3.11-15.el6_6.1.x86_64 gdk-pixbuf2-2.24.1-6.el6_7.x86_64 glib2-2.28.8-4.el6.x86_64 glibc-2.12-1.166.el6_7.3.x86_64 gtk2-2.24.23-6.el6.x86_64 gtk2-engines-2.18.4-5.el6.centos.x86_64 libX11-1.6.0-6.el6.x86_64 libXau-1.0.6-4.el6.x86_64 libXcomposite-0.4.3-4.el6.x86_64 libXcursor-1.1.14-2.1.el6.x86_64 libXdamage-1.1.3-4.el6.x86_64 libXext-1.3.2-2.1.el6.x86_64 libXfixes-5.0.1-2.1.el6.x86_64 libXi-1.7.2-2.2.el6.x86_64 libXinerama-1.1.3-2.1.el6.x86_64 libXrandr-1.4.1-2.1.el6.x86_64 libXrender-0.9.8-2.1.el6.x86_64 libXtst-1.2.2-2.1.el6.x86_64 libpng-1.2.49-2.el6_7.x86_64 libselinux-2.0.94-5.8.el6.x86_64 libxcb-1.9.1-3.el6.x86_64 pango-1.28.1-10.el6.x86_64 pixman-0.32.4-4.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) where
#0  0x00007ff4f55b83ce in raise () from /opt/glibc/glibc-2.14/libc.so.6
#1  0x00007ff4f55b9815 in abort () from /opt/glibc/glibc-2.14/libc.so.6
#2  0x00007ff4f4c2f0f5 in os::abort(bool, void*, void const*) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
#3  0x00007ff4f4f0910e in VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
#4  0x00007ff4f4f099fb in VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*, char const*, ...) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
#5  0x00007ff4f4f09a2e in VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
#6  0x00007ff4f4c3acff in JVM_handle_linux_signal () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
#7  0x00007ff4f4c2cd68 in signalHandler(int, siginfo*, void*) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
#8  0x00007ff4a580de18 in WTF::jscSignalHandler(int, siginfo_t*, void*) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#9  <signal handler called>
#10 0x00007ff4a57b1ecc in WTFCrash () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#11 0x00007ff4a57d4625 in WTF::Thread::create(char const*, WTF::Function<void ()()>&&) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#12 0x00007ff4a57b442e in WTF::AutomaticThread::start(WTF::AbstractLocker const&) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#13 0x00007ff4a57b463b in WTF::AutomaticThreadCondition::notifyAll(WTF::AbstractLocker const&) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#14 0x00007ff4a41f682c in JSC::VMTraps::fireTrap(JSC::VMTraps::EventType) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#15 0x00007ff4a41f6a2e in WTF::Function<void ()()>::CallableWrapper<JSC::Watchdog::startTimer(WTF::Seconds)::{lambda()#1}>::call() () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#16 0x00007ff4a581435c in WTF::Function<void ()()>::CallableWrapper<WTF::WorkQueue::dispatchAfter(WTF::Seconds, WTF::Function<void ()()>&&)::{lambda()#1}>::call() () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#17 0x00007ff4a58138aa in WTF::RunLoop::runImpl(WTF::RunLoop::RunMode) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#18 0x00007ff4a57d407c in WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#19 0x00007ff4a580f889 in WTF::wtfThreadEntryPoint(void*) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
#20 0x00007ff4f5d2ea51 in start_thread () from /lib64/libpthread.so.0
#21 0x00007ff4f565dffd in clone () from /opt/glibc/glibc-2.14/libc.so.6
(gdb) bt full
#0  0x00007ff4f55b83ce in raise () from /opt/glibc/glibc-2.14/libc.so.6
No symbol table info available.
#1  0x00007ff4f55b9815 in abort () from /opt/glibc/glibc-2.14/libc.so.6
No symbol table info available.
#2  0x00007ff4f4c2f0f5 in os::abort(bool, void*, void const*) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
No symbol table info available.
#3  0x00007ff4f4f0910e in VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
No symbol table info available.
#4  0x00007ff4f4f099fb in VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*, char const*, ...) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
No symbol table info available.
#5  0x00007ff4f4f09a2e in VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
No symbol table info available.
#6  0x00007ff4f4c3acff in JVM_handle_linux_signal () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
No symbol table info available.
#7  0x00007ff4f4c2cd68 in signalHandler(int, siginfo*, void*) () from /usr/lib/jvm/adoptopenjdk-11-hotspot/lib/server/libjvm.so
No symbol table info available.
#8  0x00007ff4a580de18 in WTF::jscSignalHandler(int, siginfo_t*, void*) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#9  <signal handler called>
No symbol table info available.
#10 0x00007ff4a57b1ecc in WTFCrash () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#11 0x00007ff4a57d4625 in WTF::Thread::create(char const*, WTF::Function<void ()()>&&) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#12 0x00007ff4a57b442e in WTF::AutomaticThread::start(WTF::AbstractLocker const&) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#13 0x00007ff4a57b463b in WTF::AutomaticThreadCondition::notifyAll(WTF::AbstractLocker const&) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#14 0x00007ff4a41f682c in JSC::VMTraps::fireTrap(JSC::VMTraps::EventType) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#15 0x00007ff4a41f6a2e in WTF::Function<void ()()>::CallableWrapper<JSC::Watchdog::startTimer(WTF::Seconds)::{lambda()#1}>::call() () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#16 0x00007ff4a581435c in WTF::Function<void ()()>::CallableWrapper<WTF::WorkQueue::dispatchAfter(WTF::Seconds, WTF::Function<void ()()>&&)::{lambda()#1}>::call() () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#17 0x00007ff4a58138aa in WTF::RunLoop::runImpl(WTF::RunLoop::RunMode) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#18 0x00007ff4a57d407c in WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#19 0x00007ff4a580f889 in WTF::wtfThreadEntryPoint(void*) () from /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so
No symbol table info available.
#20 0x00007ff4f5d2ea51 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#21 0x00007ff4f565dffd in clone () from /opt/glibc/glibc-2.14/libc.so.6
No symbol table info available.

---------------  T H R E A D  ---------------

Current thread (0x00007ff436fdf000):  JavaThread "Thread-551261" daemon [_thread_in_native, id=4967, stack(0x00007ff460100000,0x00007ff460b00000)]

Stack: [0x00007ff460100000,0x00007ff460b00000],  sp=0x00007ff460afebe0,  free space=10234k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libjfxwebkit.so+0x1ffeecc]  WTFCrash+0x1c
C  [libjfxwebkit.so+0x2021625]
C  [libjfxwebkit.so+0x200142e]  WTF::AutomaticThread::start(WTF::AbstractLocker const&)+0x5e
C  [libjfxwebkit.so+0x200163b]  WTF::AutomaticThreadCondition::notifyAll(WTF::AbstractLocker const&)+0x9b
C  [libjfxwebkit.so+0xa4382c]  JSC::VMTraps::fireTrap(JSC::VMTraps::EventType)+0x9c
C  [libjfxwebkit.so+0xa43a2e]  WTF::Function<void ()>::CallableWrapper<JSC::Watchdog::startTimer(WTF::Seconds)::{lambda()#1}>::call()+0x3e
C  [libjfxwebkit.so+0x206135c]  WTF::Function<void ()>::CallableWrapper<WTF::WorkQueue::dispatchAfter(WTF::Seconds, WTF::Function<void ()>&&)::{lambda()#1}>::call()+0x4c
C  [libjfxwebkit.so+0x20608aa]  WTF::RunLoop::runImpl(WTF::RunLoop::RunMode)+0x52a
C  [libjfxwebkit.so+0x202107c]  WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)+0x6c
C  [libjfxwebkit.so+0x205c889]  WTF::wtfThreadEntryPoint(void*)+0x9


siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00000000bbadbeef

Register to memory mapping:

RAX=0x00000000bbadbeef is an unknown value
RBX=0x00007ff3ad879050 points into unknown readable memory: 0x0000006000000002 | 02 00 00 00 60 00 00 00
RCX=0x00007ff4f5d33dd4: pthread_once+0x0000000000000074 in /lib64/libpthread.so.0 at 0x00007ff4f5d27000
RDX=0x0 is NULL
RSP=0x00007ff460afebe0 is pointing into the stack for thread: 0x00007ff436fdf000
RBP=0x00007ff460afebe0 is pointing into the stack for thread: 0x00007ff436fdf000
RSI=0x00007ff460afea48 is pointing into the stack for thread: 0x00007ff436fdf000
RDI=0x00007ff460afea48 is pointing into the stack for thread: 0x00007ff436fdf000
R8 =0x00007ff460afe870 is pointing into the stack for thread: 0x00007ff436fdf000
R9 =0x00007ff460afea10 is pointing into the stack for thread: 0x00007ff436fdf000
R10=0x6572616873206d6f is an unknown value
R11=0x0000000000000206 is an unknown value
R12=0x00007ff3ad879070 points into unknown readable memory: 0x0000000000000001 | 01 00 00 00 00 00 00 00
R13=0x00007ff460afec38 is pointing into the stack for thread: 0x00007ff436fdf000
R14=0x00007ff460afec30 is pointing into the stack for thread: 0x00007ff436fdf000
R15=0x00007ff4a5b3f52c: <offset 0x000000000238c52c> in /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so at 0x00007ff4a37b3000


Registers:
RAX=0x00000000bbadbeef, RBX=0x00007ff3ad879050, RCX=0x00007ff4f5d33dd4, RDX=0x0000000000000000
RSP=0x00007ff460afebe0, RBP=0x00007ff460afebe0, RSI=0x00007ff460afea48, RDI=0x00007ff460afea48
R8 =0x00007ff460afe870, R9 =0x00007ff460afea10, R10=0x6572616873206d6f, R11=0x0000000000000206
R12=0x00007ff3ad879070, R13=0x00007ff460afec38, R14=0x00007ff460afec30, R15=0x00007ff4a5b3f52c
RIP=0x00007ff4a57b1ecc, EFLAGS=0x0000000000010202, CSGSFS=0x0000000000000033, ERR=0x0000000000000006
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007ff460afebe0)
0x00007ff460afebe0:   00007ff460afec20 00007ff4a57d4625
0x00007ff460afebf0:   00007ff4f6995de0 00007ff43cbcaa28
0x00007ff460afec00:   00007ff43cbcaa20 00007ff460afecb8
0x00007ff460afec10:   00007ff4a279d288 0000000000000001 

Instructions: (pc=0x00007ff4a57b1ecc)
0x00007ff4a57b1dcc:   e8 cf f8 01 00 48 8b 05 80 a7 4e 02 48 89 df 44
0x00007ff4a57b1ddc:   89 75 c0 4c 89 6d d0 c7 45 c4 00 00 00 00 4c 8d
0x00007ff4a57b1dec:   60 10 4c 89 65 b8 e8 99 f8 01 00 48 8d 7d c0 31
0x00007ff4a57b1dfc:   d2 48 89 c6 e8 bb 18 02 00 48 89 df e8 73 f8 01
0x00007ff4a57b1e0c:   00 48 89 df 4c 89 65 b8 e8 a7 f8 01 00 48 83 c4
0x00007ff4a57b1e1c:   30 5b 41 5c 41 5d 41 5e 5d c3 66 2e 0f 1f 84 00
0x00007ff4a57b1e2c:   00 00 00 00 55 48 89 e5 53 48 8d 9d e0 fe ff ff
0x00007ff4a57b1e3c:   48 8d b5 dc fe ff ff 48 81 ec 28 01 00 00 c7 85
0x00007ff4a57b1e4c:   dc fe ff ff 21 00 00 00 48 89 df e8 34 17 02 00
0x00007ff4a57b1e5c:   8b 85 dc fe ff ff 48 8d 7b 10 8d 70 fe e8 42 ff
0x00007ff4a57b1e6c:   ff ff 48 81 c4 28 01 00 00 5b 5d c3 0f 1f 84 00
0x00007ff4a57b1e7c:   00 00 00 00 55 48 89 e5 53 89 fb 48 83 ec 08 e8
0x00007ff4a57b1e8c:   60 a9 52 fe 8d bb 80 00 00 00 e8 e5 ac 52 fe 0f
0x00007ff4a57b1e9c:   1f 44 00 00 55 48 89 3d 70 21 52 02 48 89 e5 5d
0x00007ff4a57b1eac:   c3 0f 1f 00 48 8b 05 61 21 52 02 55 48 89 e5 48
0x00007ff4a57b1ebc:   85 c0 74 02 ff d0 e8 29 a9 52 fe b8 ef be ad bb
0x00007ff4a57b1ecc:   c7 00 00 00 00 00 0f 0b 66 66 66 2e 0f 1f 84 00
0x00007ff4a57b1edc:   00 00 00 00 55 48 89 e5 e8 87 a6 52 fe 0f 1f 80
0x00007ff4a57b1eec:   00 00 00 00 55 48 8d 3d 18 fc ff ff 48 89 e5 e8
0x00007ff4a57b1efc:   a0 ff ff ff 48 8d 35 79 ff ff ff bf 04 00 00 00
0x00007ff4a57b1f0c:   e8 7f b2 52 fe 48 8d 35 68 ff ff ff bf 05 00 00
0x00007ff4a57b1f1c:   00 e8 6e b2 52 fe 48 8d 35 57 ff ff ff bf 08 00
0x00007ff4a57b1f2c:   00 00 e8 5d b2 52 fe 48 8d 35 46 ff ff ff bf 07
0x00007ff4a57b1f3c:   00 00 00 e8 4c b2 52 fe 48 8d 35 35 ff ff ff bf
0x00007ff4a57b1f4c:   0b 00 00 00 e8 3b b2 52 fe 48 8d 35 24 ff ff ff
0x00007ff4a57b1f5c:   bf 1f 00 00 00 e8 2a b2 52 fe 48 8d 35 13 ff ff
0x00007ff4a57b1f6c:   ff bf 0d 00 00 00 e8 19 b2 52 fe 48 8d 35 02 ff
0x00007ff4a57b1f7c:   ff ff bf 18 00 00 00 e8 08 b2 52 fe 5d 48 8d 35
0x00007ff4a57b1f8c:   f0 fe ff ff bf 19 00 00 00 e9 f6 b1 52 fe 66 0f
0x00007ff4a57b1f9c:   1f 44 00 00 55 31 c0 48 89 e5 5d c3 0f 1f 84 00
0x00007ff4a57b1fac:   00 00 00 00 55 48 89 e5 41 57 41 56 41 55 41 54
0x00007ff4a57b1fbc:   49 89 cc 53 48 81 ec f8 00 00 00 84 c0 48 89 bd 


Stack slot to memory mapping:
stack at sp + 0 slots: 0x00007ff460afec20 is pointing into the stack for thread: 0x00007ff436fdf000
stack at sp + 1 slots: 0x00007ff4a57d4625: <offset 0x0000000002021625> in /home/ods/.openjfx/cache/11.0.2/libjfxwebkit.so at 0x00007ff4a37b3000
stack at sp + 2 slots: 0x00007ff4f6995de0 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
stack at sp + 3 slots: 0x00007ff43cbcaa28 points into unknown readable memory: 0x00007fe400000003 | 03 00 00 00 e4 7f 00 00
stack at sp + 4 slots: 0x00007ff43cbcaa20 points into unknown readable memory: 0x00007ff4a7b07b18 | 18 7b b0 a7 f4 7f 00 00
stack at sp + 5 slots: 0x00007ff460afecb8 is pointing into the stack for thread: 0x00007ff436fdf000
stack at sp + 6 slots: 0x00007ff4a279d288 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
stack at sp + 7 slots: 0x0000000000000001 is an unknown value
```

**Comment by karianna** [comment]
@vlapra please try the latest 11.0.17 binaries from adoptium.net
