### ISSUE TITLE
Backport the JDK-8280132 issue correction on JDK 11 and 17

### ISSUE THREAD

**Issue by SuperPat45** [adoptium/adoptium-support#639]
### Please provide a brief summary of the bug

My production server crash due to this error: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:93)
	at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:80)

This error is already reported in the JDK tracker; https://bugs.openjdk.org/browse/JDK-8280132
And it is fixed in JDK 19 in this commit: https://github.com/openjdk/jdk/commit/2f46af05ce2d43e19e0095680eb3a52fd904c774

Can you backport it in temurin 11 and 17 ?

### Expected Results

no exception

### Actual Results

java.lang.IllegalArgumentException: Comparison method violates its general contract! is thrown

### What Java Version are you using?

11.0.16

### Relevant log output

```shell
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:93)
	at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:80)
```

**Comment by karianna** [comment]
Will be fixed in 17.0.7

**Comment by gdams** [comment]
Backport to 11u-dev: https://github.com/openjdk/jdk11u-dev/pull/2053
