### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by RiotPanda19** [adoptium/adoptium-support#698]
### Please provide a brief summary of the bug

every time I try to launch with feather it always just crashes as soon as the minecraft window comes up and never works i've tried reinstalling re logging in and nothing works
[latest.log](https://github.com/adoptium/adoptium-support/files/10499668/latest.log)
I have attached the error logs 

### Please provide steps to reproduce where possible

Download feather
Log in
Launch minecraft
Game crashes

### Expected Results

minecraft to load and allow me to play with feather

### Actual Results

it crashed 

### What Java Version are you using?

64 bit java

### What is your operating system and platform?

windows 11 and laptop

### How did you install Java?

https://www.java.com/en/download/

### Did it work before?

```shell
No
```

### Did you test with other Java versions?

```shell
No
```

### Relevant log output

```shell
info: CONNECTING TO SERVER undefined
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start::bindings] server: None
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Loading version
info: {"versionSize":220833314,"state":{"VersionLoading":true},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":0}
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Finished loading version
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Finished moving mods
info: {"versionSize":220833314,"state":{"Downloading":["Libraries","Mods","Assets","Jre"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":78908}
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Preparing assets
[2023-01-25T13:20:28Z INFO  rust_launcher::start] Preparing JRE
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Preparing libraries
info: {"versionSize":220833314,"state":{"Downloading":["Libraries","Mods","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":43226789}
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Preparing mods
info: {"versionSize":220833314,"state":{"Downloading":["Libraries","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":83939939}
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Finished preparing mods
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Finished preparing assets
info: {"versionSize":220833314,"state":{"Downloading":["Libraries"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":707307465}
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Finished preparing libraries
[2023-01-25T13:20:28Z INFO  rust_launcher::start] Preparing registry
info: {"versionSize":220833314,"state":{"Jvm":true},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":801323835}
info: [2023-01-25T13:20:28Z INFO  rust_launcher::start] Finished preparing registry
info: [2023-01-25T13:20:28Z INFO  rust_launcher::common::launch] starting JVM with arguments: ["-Djava.library.path=libraries/native\\net/digitalingot/fcef-windows/0.0.5\\extracted/;libraries/native\\net/digitalingot/fwebp-windows/0.0.1\\extracted/;libraries/native\\de/jcm/discord-game-sdk4j-windows/0.5.4\\extracted/;libraries/native\\org/jitsi/jnopus/1.0\\extracted/;libraries/native\\org/lwjgl/lwjgl/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-jemalloc/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-openal/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-opengl/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-glfw/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-stb/3.3.1\\extracted/;libraries/native\\org/lwjgl/lwjgl-tinyfd/3.3.1\\extracted/;libraries/native\\com/mojang/text2speech/1.13.9\\extracted/", "--add-opens=java.desktop/java.awt.event=ALL-UNNAMED", "--add-opens=java.desktop/java.awt.color=ALL-UNNAMED", "--add-opens=java.desktop/java.awt=ALL-UNNAMED", "--add-opens=java.base/java.lang=ALL-UNNAMED", "-Xmx2048M", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseG1GC", "-XX:G1NewSizePercent=20", "-XX:G1ReservePercent=20", "-XX:MaxGCPauseMillis=50", "-XX:G1HeapRegionSize=32M", "-Dlog4j2.formatMsgNoLookups=true", "-XX:ErrorFile=feather/java_error.log", "-Djavax.accessibility.assistive_technologies=", "-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT", "-cp", "libraries\\java\\net/minecraft/client/1.19.3/minecraft-1.19.3.jar;libraries\\java\\net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar;libraries\\java\\net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar;libraries\\java\\net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar;libraries\\java\\net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar;libraries\\java\\org/ow2/asm/asm/9.3/asm-9.3.jar;libraries\\java\\org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar;libraries\\java\\org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar;libraries\\java\\org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar;libraries\\java\\org/ow2/asm/asm-util/9.3/asm-util-9.3.jar;libraries\\java\\net/fabricmc/intermediary/1.19.3/intermediary-1.19.3.jar;libraries/java\\net/fabricmc/fabric-loader/0.14.13/fabric-loader-0.14.13.jar;libraries\\java\\de/javagl/obj/0.3.0/obj-0.3.0.jar;libraries\\java\\de/jcm/discord-game-sdk4j/0.5.4/discord-game-sdk4j-0.5.4;libraries\\java\\net/digitalingot/feather-server-api-proto/1.1-SNAPSHOT/feather-server-api-proto-1.1-SNAPSHOT.jar;libraries\\java\\net/digitalingot/rust-extension/1.0.7/rust-extension-1.0.7.jar;libraries\\java\\net/digitalingot/fcef/0.0.5/fcef-0.0.5.jar;libraries\\java\\net/digitalingot/fwebp/0.0.1/fwebp-0.0.1.jar;libraries\\java\\net/digitalingot/feather-server-api/messaging/0.0.1/messaging-0.0.1-SNAPSHOT.jar;libraries\\java\\org/jitsi/libjitsi/1.0-CUSTOM/libjitsi-1.0-CUSTOM.jar;libraries\\java\\org/jitsi/jitsi-utils/1.0-45-gc3afb76/jitsi-utils-1.0-45-gc3afb76.jar;libraries\\java\\org/capnproto/runtime/0.1.10/runtime-0.1.10.jar;libraries\\java\\com/google/inject/guice/5.1.0/guice-vendored-5.1.0.jar;libraries\\java\\javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar;libraries\\java\\com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar;libraries\\java\\com/google/code/gson/gson/2.10/gson-2.10.jar;libraries\\java\\com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar;libraries\\java\\com/google/guava/guava/31.1-jre/guava-31.1-jre.jar;libraries\\java\\com/ibm/icu/icu4j/71.1/icu4j-71.1.jar;libraries\\java\\com/mojang/authlib/3.16.29/authlib-3.16.29.jar;libraries\\java\\com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar;libraries\\java\\com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar;libraries\\java\\com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar;libraries\\java\\com/mojang/javabridge/2.0.25/javabridge-2.0.25.jar;libraries\\java\\com/mojang/logging/1.1.1/logging-1.1.1.jar;libraries\\java\\com/mojang/patchy/2.2.10/patchy-2.2.10.jar;libraries\\java\\com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar;libraries\\java\\commons-codec/commons-codec/1.15/commons-codec-1.15.jar;libraries\\java\\commons-io/commons-io/2.11.0/commons-io-2.11.0.jar;libraries\\java\\commons-logging/commons-logging/1.2/commons-logging-1.2.jar;libraries\\java\\io/netty/netty-codec-http/4.1.82.Final/netty-codec-http-4.1.82.Final.jar;libraries\\java\\io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar;libraries\\java\\io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar;libraries\\java\\io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar;libraries\\java\\io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar;libraries\\java\\io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar;libraries\\java\\io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar;libraries\\java\\io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar;libraries\\java\\io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar;libraries\\java\\it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar;libraries\\java\\net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar;libraries\\java\\net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar;libraries\\java\\net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar;libraries\\java\\org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar;libraries\\java\\org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar;libraries\\java\\org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar;libraries\\java\\org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar;libraries\\java\\org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar;libraries\\java\\org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar;libraries\\java\\org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar;libraries\\java\\org/joml/joml/1.10.5/joml-1.10.5.jar;libraries\\java\\org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar;libraries\\java\\org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar;libraries\\java\\org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar", "net.digitalingot.rustextension.ProxiedStart", "net.fabricmc.loader.launch.knot.KnotClient", "--username", "RiotPanda", "--version", "1.19.3-feather", "--gameDir", "C:\\Users\\kirst\\AppData\\Roaming/.minecraft", "--assetsDir", "assets", "--assetIndex", "1.19.3-feather-game", "--uuid", "ede4f378b66c4a0d98522f2c712e24f7", "--accessToken", "<hidden>", "--userType", "msa", "--versionType", "feather"]
info: sending javaw pid
info: starting cleanup
info: [13:20:30] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.13
info: [13:20:30] [main/INFO]: Loading 59 mods:
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- controlling 10.0+9
	- entityculling 1.5.2-mc1.19.3
	- fabric-api 0.72.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.29+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.11+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.21+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.0+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.38+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.46+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.4+1134c5b885 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.42+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.8+1134c5b885 via fabric-api
	- fabric-item-group-api-v1 2.1.11+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.30+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.28+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.26+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.33+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.0+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.4+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.0+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.0+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.29+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.32+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.0+6dc0edd785 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.2+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.40+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.7+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.14+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
	- fabricloader 0.14.13
	- feather 1.0.0-SNAPSHOT
	- java 17
	- minecraft 1.19.3
	- starlight 1.1.1+fabric.ae22326
	- worldedit 7.2.13+46576cc
info: [13:20:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/kirst/AppData/Roaming/.minecraft/libraries/java/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
info: [13:20:30] [main/INFO]: Compatibility level set to JAVA_17
info: [13:20:31] [main/WARN]: Error loading class: net/optifine/Config (java.lang.ClassNotFoundException: net/optifine/Config)
info: [13:20:39] [main/INFO]: Building unoptimized datafixer
info: [13:20:42] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
info: [13:20:43] [Render thread/INFO]: Setting user: RiotPanda
info: [13:20:44] [Render thread/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@2248378e]
info: [13:20:44] [Render thread/INFO]: WorldEdit for Fabric (version 7.2.13+46576cc) is loaded
info: [13:20:44] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
info: [13:20:45] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
info: [13:20:46] [Render thread/WARN]: Missing metadata in pack file/BigHead (1).zip
info: [13:20:46] [Render thread/ERROR]: Failed to open pack C:\Users\kirst\AppData\Roaming\.minecraft\resourcepacks\BigHead.zip
java.util.zip.ZipException: invalid CEN header (bad entry name)
	at java.util.zip.ZipFile$Source.zerror(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile$Source.checkAndAddEntry(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile$Source.get(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
	at net.minecraft.class_3258.method_14399(class_3258.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_3258.method_14391(class_3258.java:72) ~[client-intermediary.jar:?]
	at net.minecraft.class_3258.method_14410(class_3258.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.ch(class_3283.java:1062) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:1053) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[minecraft-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.14.13.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) ~[rust-extension-1.0.7.jar:?]
info: [13:20:46] [Render thread/WARN]: Missing metadata in pack file/BigHead.zip
info: [13:20:46] [Render thread/WARN]: Missing metadata in pack file/ModernaHD-1.17-v1.0.zip
info: [13:20:47] [Render thread/INFO]: Narrator library for x64 successfully loaded
info: [13:20:47] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (Controlling For Fabric, EntityCulling-Fabric, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Feather Client, Starlight, WorldEdit)
info: [13:20:48] [Worker-Main-11/WARN]: Texture feather:block/glass with size 1x1 limits mip level from 4 to 0
info: [13:20:48] [Worker-Main-11/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
info: [FBD] Primary: NVIDIA GeForce RTX 2060. High: NVIDIA GeForce RTX 2060. Low: NVIDIA GeForce RTX 2060.
info: [FBD] Hardware Acceleration: 1
info: [13:20:51] [Render thread/INFO]: [STDOUT]: initialize on Thread[Render thread,5,main] with library path libraries/native\net/digitalingot/fcef-windows/0.0.5\extracted/
error: [0125/132051.984:FATAL:v8_initializer.cc(430)] Error loading V8 startup snapshot file
info: #
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_windows_x86.cpp:143), pid=13620, tid=15200
#  guarantee(result == EXCEPTION_CONTINUE_EXECUTION) failed: Unexpected result from topLevelExceptionFilter
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
info: # An error report file with more information is saved as:
# feather/java_error.log
info: #
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
info: [2023-01-25T13:20:52Z INFO  rust_launcher::start::bindings] launch stalled
```

**Comment by karianna** [comment]
You can try the lastest 17.0.6, but this is a crash due to the mod, so you'll need to report it to the mod author.
