### ISSUE TITLE
jpackage ClassCastException when adding additional launcher

### ISSUE THREAD

**Issue by airsquared** [adoptium/adoptium-support#769]
### Please provide a brief summary of the bug

When running jpackage and adding `--add-launcher`, it throws `ClassCastException`.

### Please provide steps to reproduce where possible

https://github.com/airsquared/jpackage_error

Run `./build.sh` or look at the GitHub Actions [logs](https://github.com/airsquared/jpackage_error/actions).

### Expected Results

It should succeed and generate the platform specific installer.

### Actual Results

Just prints:

```
java.lang.ClassCastException: class java.util.ImmutableCollections$List12 cannot be cast to class java.lang.String (java.util.ImmutableCollections$List12 and java.lang.String are in module java.base of loader 'bootstrap')
```

### What Java Version are you using?

openjdk 20 2023-03-21 OpenJDK Runtime Environment Temurin-20+36 (build 20+36) OpenJDK 64-Bit Server VM Temurin-20+36 (build 20+36, mixed mode, sharing)

### What is your operating system and platform?

On Intel (GitHub Actions runners):

Ubuntu 22.04.2, Microsoft Windows Server 2022 10.0.20348, macOS 12.6.4

### How did you install Java?

From the latest GitHub Actions package:

```
uses: actions/setup-java@v3
with:
  java-version: '20'
  distribution: 'temurin'
```

### Did you test with the latest update version?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
Java 20 and Java 17
```

### Relevant log output

```Shell
Caused by: java.lang.ClassCastException: class java.util.ImmutableCollections$List12 cannot be cast to class java.lang.String (java.util.ImmutableCollections$List12 and java.lang.String are in module java.base of loader 'bootstrap')
	at jdk.jpackage/jdk.jpackage.internal.LauncherData.lambda$getPathListParameter$5(LauncherData.java:309)
	at jdk.jpackage/jdk.jpackage.internal.LauncherData.getPathParam(LauncherData.java:271)
	at jdk.jpackage/jdk.jpackage.internal.LauncherData.getPathListParameter(LauncherData.java:308)
	at jdk.jpackage/jdk.jpackage.internal.LauncherData.getModulePath(LauncherData.java:293)
	at jdk.jpackage/jdk.jpackage.internal.LauncherData.createModular(LauncherData.java:135)
	at jdk.jpackage/jdk.jpackage.internal.LauncherData.create(LauncherData.java:115)
	at jdk.jpackage/jdk.jpackage.internal.StandardBundlerParam.lambda$static$0(StandardBundlerParam.java:84)
	at jdk.jpackage/jdk.jpackage.internal.BundlerParamInfo.fetchFrom(BundlerParamInfo.java:114)
	at jdk.jpackage/jdk.jpackage.internal.BundlerParamInfo.fetchFrom(BundlerParamInfo.java:88)
	at jdk.jpackage/jdk.jpackage.internal.CfgFile.initFromParams(CfgFile.java:50)
	at jdk.jpackage/jdk.jpackage.internal.AbstractAppImageBuilder.writeCfgFile(AbstractAppImageBuilder.java:65)
	at jdk.jpackage/jdk.jpackage.internal.MacAppImageBuilder.prepareApplicationFiles(MacAppImageBuilder.java:329)
	at jdk.jpackage/jdk.jpackage.internal.AppImageBundler.createAppBundle(AppImageBundler.java:187)
	at jdk.jpackage/jdk.jpackage.internal.AppImageBundler.execute(AppImageBundler.java:91)
	... 7 more
```

**Comment by karianna** [comment]
@airsquared Does it work for Java 17?  Is it both the Mac OS X and Windows hosts this fails on?

**Comment by airsquared** [comment]
@karianna No, it fails on both Java 17 and Java 20 on macOS, Windows, and Ubuntu.

**Comment by airsquared** [comment]
Is there a way I can report it myself to OpenJDK or do I need to wait for someone to do it?

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8306488

**Comment by airsquared** [comment]
Ended up fixing this myself at openjdk/jdk#14840, which was just merged. I'll try to see if I can get this backported.

**Comment by airsquared** [comment]
Backported in openjdk/jdk21u#120 and openjdk/jdk17u-dev#1717
