### ISSUE TITLE
JTable$AccessibleJTable selection listener is called after upgrading to MAC OS Sonoma 14

### ISSUE THREAD

**Issue by adriantoganel** [adoptium/adoptium-support#920]
### Please provide a brief summary of the bug

After migrating to latest MAC OS Sonoma 14.0 (23A344) we are facing problems caused the JTable$AccessibleJTable selection listener.
On the older MAC OS or Windows we do not see this listener being called.
The call stack

```
	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7164) ~[?:?]
	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7554) ~[?:?]
	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:7074) ~[?:?]
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219) ~[?:?]
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199) ~[?:?]
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246) ~[?:?]
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443) ~[?:?]
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453) ~[?:?]
	at javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(DefaultListSelectionModel.java:614) ~[?:?]
	at javax.swing.DefaultListSelectionModel.clearSelection(DefaultListSelectionModel.java:458) ~[?:?]
	at javax.swing.JTable.clearSelection(JTable.java:2124) ~[?:?]
```

Can you please help us understand  why this gets called only on the latest mac os ?

Regards,

### Please provide steps to reproduce where possible

Do some row selection in BTable

### Expected Results

On windows or old mac os JTable$AccessibleJTable is not in the listenerList list from DefaultListSelectionModel

### Actual Results

the listener is called

### What Java Version are you using?

openjdk 11.0.16.1 2022-08-12

### What is your operating system and platform?

MAC OS Sonoma 14

### Did it work before?

```Shell
before upgrading to this MAC os version
```

### Did you test with the latest update version?

```Shell
no
```

### Did you test with other Java versions?

```Shell
no
```

**Comment by karianna** [comment]
Please move to 11.0.20.1 and report back here.

**Comment by adriantoganel** [comment]
Hi,
I confirm it is reproducible with 11.0.20.1 as well.
Regards,

**Comment by karianna** [comment]
https://bugs.openjdk.org/browse/JDK-8318385

**Comment by karianna** [comment]
@adriantoganel Oracle is asking you to test with JDK 21 and see if its still an issue.  Also what is a BTable?

**Comment by adriantoganel** [comment]
Hi,
We will implement a protection in our code.
I think you can close this item. 
For now related to oracle question
- we cannot afford migrating our project to j21 but I can confirm that j17 we do not have this problem
- it is a typo, it is "selection in the table"

**Comment by adriantoganel** [comment]
Thanks for your help
