### ISSUE TITLE
Run time error of Java Temurin 21.0.1 application on macOS Catalina mac mini

### ISSUE THREAD

**Issue by Papa-26** [adoptium/adoptium-support#980]
### Please provide a brief summary of the bug

I created a statistical application https://github.com/G-String-Legacy/GS_MV in Intellij IDEA 2023.1. 
It is built with Gradle 8.5 and Temurin openjdk 21.0.1
It works properly within the IDE, and on installed versions on Linux and Windows. I pulled it to Intellij on a mini mac Catalina. It built and compiled properly. But on 'run', I got:
:run FAILED
2023-12-25 09:26:07.194 java[1985:42297] ERROR: macOS version is 10.15, which is below the minimum of 11.0

### Did you test with the latest update version?

```Shell
I used a Temurin  21 download as of today: Dec. 25 2023.
The Intellij scan report is at: https://scans.gradle.com/s/o74prjaxzjsui/console-log/task/:run?anchor=23&page=1
```

### Expected Results

I expected the application to run, as Temurin openjdk 17 had run previously

### Actual Results

it does not run, but fails

### What Java Version are you using?

openjdk 21.0.1 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

### What is your operating system and platform?

It runs on Ubuntu and Windows 10, but fails on macOS Catalina. I don't have other mac machines to try it out

### How did you install Java?

I used the default mac package installer

### Did it work before?

```Shell
worked with version 17 on mac-mini Catalina, and 21 on Ubuntu and Windows10
```

### Did you test with other Java versions?

```Shell
see above
```

### Relevant log output

```Shell
:run FAILED	
2023-12-25 09:26:07.194 java[1985:42297] ERROR: macOS version is 10.15, which is below the minimum of 11.0	
Exception in thread "main" java.lang.reflect.InvocationTargetException	
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)	
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)	
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1135)	
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError	
	at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:300)	
	at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)	
	at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)	
	at javafx.graphics@21.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)	
	at javafx.graphics@21.0.1/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)	
	at javafx.graphics@21.0.1/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)	
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)	
	... 2 more	
Caused by: java.lang.ExceptionInInitializerError	
	at javafx.graphics@21.0.1/com.sun.glass.ui.mac.MacPlatformFactory.createApplication(MacPlatformFactory.java:36)	
	at javafx.graphics@21.0.1/com.sun.glass.ui.Application.run(Application.java:146)	
	at javafx.graphics@21.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)	
	... 8 more	
Caused by: java.lang.RuntimeException: Unsupported macOS version	
	at javafx.graphics@21.0.1/com.sun.glass.ui.mac.MacApplication._initIDs(Native Method)	
	at javafx.graphics@21.0.1/com.sun.glass.ui.mac.MacApplication.<clinit>(MacApplication.java:55)	
	... 11 more
```

**Comment by karianna** [comment]
@Papa-26 Java 21+ is not supported on Catalina - you'll need to downgrade to Java 17.0.9 or upgrade your Mac OS X.
