### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by ivorymalevolentgodofevil** [adoptium/adoptium-support#983]
### Please provide a brief summary of the bug

Sever crashing on launch

### Please provide steps to reproduce where possible

I downloaded a couple of mods and tried launching the game and it crashed

### Expected Results

Not to crash

### Actual Results

Crashed

### What Java Version are you using?

java

### What is your operating system and platform?

windows

### Did it work before?

```Shell
nope
```

### Did you test with other Java versions?

```Shell
nope
```

### Relevant log output

```Shell
[INFO] [io.dogboy.serializationisbad.core.SerializationIsBad]: Initializing SerializationIsBad, implementation type: agent
I> Using policy access restrictor file:/other/jolokia/policy.xml
Jolokia: Agent started with URL http://**.**.**.**:9899/jolokia/
[ERROR] [io.dogboy.serializationisbad.core.SerializationIsBad]: Failed to load remote config file
java.net.UnknownHostException: raw.githubusercontent.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at io.dogboy.serializationisbad.core.SerializationIsBad.readRemoteConfig(SerializationIsBad.java:134)
	at io.dogboy.serializationisbad.core.SerializationIsBad.readConfig(SerializationIsBad.java:112)
	at io.dogboy.serializationisbad.core.SerializationIsBad.<init>(SerializationIsBad.java:63)
	at io.dogboy.serializationisbad.core.SerializationIsBad.init(SerializationIsBad.java:45)
	at io.dogboy.serializationisbad.agent.SerializationIsBadAgent.premain(SerializationIsBadAgent.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
[INFO] [io.dogboy.serializationisbad.core.SerializationIsBad]: Using local config file as a fallback
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.RuntimeException: You are currently using SerializationIsBad without any patch modules configured. The mod on its own doesn't do anything so please install a config file patching the vulnerabilities
	at io.dogboy.serializationisbad.core.SerializationIsBad.<init>(SerializationIsBad.java:65)
	at io.dogboy.serializationisbad.core.SerializationIsBad.init(SerializationIsBad.java:45)
	at io.dogboy.serializationisbad.agent.SerializationIsBadAgent.premain(SerializationIsBadAgent.java:16)
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 619
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 459
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x8b14ee]  jni_FatalError+0xbe
V  [libjvm.so+0xa2d932]  JvmtiExport::post_vm_initialized()+0x132
V  [libjvm.so+0xe64c4c]  Threads::create_vm(JavaVMInitArgs*, bool*)+0x95c
V  [libjvm.so+0x8bfab2]  JNI_CreateJavaVM+0x52
C  [libjli.so+0x9c6f]  JavaMain+0x8f
C  [libjli.so+0xdf69]  ThreadJavaMain+0x9

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9cee138898, pid=1, tid=7
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.9+9 (17.0.9+9) (build 17.0.9+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (17.0.9+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x28898]  abort+0x178
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /server/core.1)
#
# An error report file with more information is saved as:
# /server/hs_err_pid1.log
```

**Comment by karianna** [comment]
`You are currently using SerializationIsBad without any patch modules configured. The mod on its own doesn't do anything so please install a config file patching the vulnerabilities` is the hint here.  You'll need to check with the dogboy folks on how to install this properly.
