### ISSUE TITLE
Threads blocked on KeepAliveCache.put and KeepAliveCache.get when completing API calls

### ISSUE THREAD

**Issue by RhysB** [adoptium/adoptium-support#988]
### Please provide a brief summary of the bug

I'm developing a Java application that makes multiple calls to various APIs when a client connects, each in its own thread. However, I've been encountering significant delays in response times, sometimes taking minutes. Upon inspecting the thread dump, I found that many threads are in a BLOCKED state, waiting to acquire a monitor lock on sun.net.www.http.KeepAliveCache.put. 

Unsure if this is a bug or some sort of limitation with the default HTTP code.

Here's a snippet of the stack trace:

`"Thread-613" #844 prio=5 os_prio=0 tid=0x000001c8dfd23800 nid=0x45c waiting for monitor entry [0x000000c8a66fe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:80)
        - waiting to lock <0x00000005c0027448> (a sun.net.www.http.KeepAliveCache)
        at sun.net.www.protocol.https.HttpsClient.putInKeepAliveCache(HttpsClient.java:659)
        at sun.net.www.http.HttpClient.finished(HttpClient.java:395)
        at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:97)
        at sun.net.www.MeteredStream.justRead(MeteredStream.java:93)
        at sun.net.www.MeteredStream.read(MeteredStream.java:135)
        - locked <0x000000062e959300> (a sun.net.www.http.KeepAliveStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3456)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x000000062eaa9138> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read(BufferedReader.java:182)
        - locked <0x000000062eaa9138> (a java.io.InputStreamReader)`

### Did you test with the latest update version?

```Shell
Yes
```

### Expected Results

HTTP requests would complete concurrently without monitor locks blocking multiple threads for long durations of time.

### Actual Results

Multiple threads getting stuck on sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:80) causing hangs.

### What Java Version are you using?

openjdk version "1.8.0_392" OpenJDK Runtime Environment (Temurin)(build 1.8.0_392-b08) OpenJDK 64-Bit Server VM (Temurin)(build 25.392-b08, mixed mode)

### What is your operating system and platform?

Windows Server 2022 x64

### How did you install Java?

The latest version was installed utilizing the .msi file.

### Did it work before?

```Shell
The issue was first observed on 362 with it still occurring on 392.
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
Original Stack Traces:

"Thread-613" #844 prio=5 os_prio=0 tid=0x000001c8dfd23800 nid=0x45c waiting for monitor entry [0x000000c8a66fe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:80)
        - waiting to lock <0x00000005c0027448> (a sun.net.www.http.KeepAliveCache)
        at sun.net.www.protocol.https.HttpsClient.putInKeepAliveCache(HttpsClient.java:659)
        at sun.net.www.http.HttpClient.finished(HttpClient.java:395)
        at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:97)
        at sun.net.www.MeteredStream.justRead(MeteredStream.java:93)
        at sun.net.www.MeteredStream.read(MeteredStream.java:135)
        - locked <0x000000062e959300> (a sun.net.www.http.KeepAliveStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3456)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x000000062eaa9138> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read(BufferedReader.java:182)
        - locked <0x000000062eaa9138> (a java.io.InputStreamReader)

After adding -Dhttp.keepAlive=false:

"Thread-127" #210 prio=5 os_prio=0 tid=0x00000140a3e5a000 nid=0x2abc waiting for monitor entry [0x0000003224efe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sun.net.www.http.KeepAliveCache.get(KeepAliveCache.java:156)
        - waiting to lock <0x00000005c0026570> (a sun.net.www.http.KeepAliveCache)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:329)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1342)
        - locked <0x0000000741f29bb8> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1317)
        - locked <0x0000000741f29bb8> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
        - locked <0x0000000741f299f8> (a sun.net.www.protocol.https.HttpsURLConnectionImpl)
        at com.johnymuffin.beta.legacyminecraft.pinger.LegacyMinecraftPinger.lambda$null$0(LegacyMinecraftPinger.java:127)
        at com.johnymuffin.beta.legacyminecraft.pinger.LegacyMinecraftPinger$$Lambda$223/1437347973.run(Unknown Source)
        at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"Thread-113" #194 prio=5 os_prio=0 tid=0x00000140a3e5d800 nid=0xf38 waiting for monitor entry [0x000000321eefe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sun.net.www.http.KeepAliveCache.get(KeepAliveCache.java:156)
        - waiting to lock <0x00000005c0026570> (a sun.net.www.http.KeepAliveCache)
        at sun.net.www.http.HttpClient.New(HttpClient.java:303)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1228)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        - locked <0x0000000799144c28> (a sun.net.www.protocol.http.HttpURLConnection)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        - locked <0x0000000799144c28> (a sun.net.www.protocol.http.HttpURLConnection)
        at java.net.URL.openStream(URL.java:1093)
        at com.johnymuffin.jban.core.JsonReader.readJsonFromUrl(JsonReader.java:24)
        at com.johnymuffin.jban.beta.JBListener.lambda$onPlayerPreLoginEvent$3(JBListener.java:69)
        at com.johnymuffin.jban.beta.JBListener$$Lambda$226/1010522231.run(Unknown Source)
        at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"Thread-111" #192 prio=5 os_prio=0 tid=0x00000140a3e5b000 nid=0xae8 waiting for monitor entry [0x0000003225cfe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sun.net.www.http.KeepAliveCache.get(KeepAliveCache.java:156)
        - waiting to lock <0x00000005c0026570> (a sun.net.www.http.KeepAliveCache)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:329)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
        at com.johnymuffin.beta.evolutioncore.BetaEvolutionsUtils.readJsonFromUrlWithTimeout(BetaEvolutionsUtils.java:345)
        at com.johnymuffin.beta.evolutioncore.BetaEvolutionsUtils.readJsonFromUrl(BetaEvolutionsUtils.java:335)
        at com.johnymuffin.beta.evolutioncore.BetaEvolutionsUtils.getJSONFromURL(BetaEvolutionsUtils.java:368)
        at com.johnymuffin.beta.evolutioncore.BetaEvolutionsUtils.verifyUserWithNode(BetaEvolutionsUtils.java:138)
        at com.johnymuffin.beta.evolutioncore.BetaEvolutionsUtils.verifyUser(BetaEvolutionsUtils.java:100)
        at com.johnymuffin.beta.evolutioncore.listener.EvolutionPlayerListener.lambda$onPlayerPreLogin$1(EvolutionPlayerListener.java:41)
        at com.johnymuffin.beta.evolutioncore.listener.EvolutionPlayerListener$$Lambda$232/1445565135.run(Unknown Source)
        at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None

"Thread-110" #191 prio=5 os_prio=0 tid=0x00000140a3e59800 nid=0x5fc waiting for monitor entry [0x0000003225bfe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sun.net.www.http.KeepAliveCache.get(KeepAliveCache.java:156)
        - waiting to lock <0x00000005c0026570> (a sun.net.www.http.KeepAliveCache)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:329)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
        at com.johnymuffin.beta.jdetector.utils.BetaEvolutionsUtils.readJsonFromUrlWithTimeout(BetaEvolutionsUtils.java:351)
        at com.johnymuffin.beta.jdetector.utils.BetaEvolutionsUtils.readJsonFromUrl(BetaEvolutionsUtils.java:341)
        at com.johnymuffin.beta.jdetector.utils.BetaEvolutionsUtils.getJSONFromURL(BetaEvolutionsUtils.java:377)
        at com.johnymuffin.beta.jdetector.utils.BetaEvolutionsUtils.verifyUserWithNode(BetaEvolutionsUtils.java:144)
        at com.johnymuffin.beta.jdetector.utils.BetaEvolutionsUtils.verifyUser(BetaEvolutionsUtils.java:101)
        at com.johnymuffin.beta.jdetector.JListener.lambda$onPlayerPreLogin$1(JListener.java:43)
        at com.johnymuffin.beta.jdetector.JListener$$Lambda$229/1064093256.run(Unknown Source)
        at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None
```

**Comment by karianna** [comment]
@RhysB It's hard to know without seeing your client code.  This might be a better question for StackOverflow unless you're not seeing this with other versions of Java or a different vendor of OpenJDK.
