### ISSUE TITLE
Akis kart izleme (6.5.4) throws error during installation on MacOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by taraniss** [adoptium/adoptium-support#998]
### Please provide a brief summary of the bug

Akis kart izleme throws error during installation on MacOS Sonoma 14.2.1 and it can't read the card.

<img width="400" alt="Screenshot 2024-01-21 at 17 57 37" src="https://github.com/adoptium/adoptium-support/assets/8179224/1451412e-33aa-45d6-bf88-23bd072ba746">

### Did you test with the latest update version?

```Shell
Tested with AKIA 6.5.4
```

### Please provide steps to reproduce where possible

Just click next on the installer.

### Expected Results

For it to not throw error.

### Actual Results

Throws error.

### What Java Version are you using?

java 17.0.7 2023-04-18 LTS Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224) Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

### What is your operating system and platform?

Apple M1 Max, MacOS Sonoma 14.2.1

### How did you install Java?

From https://www.java.com/en/download/manual.jsp

### Did it work before?

```Shell
It's the first time I try to install AKIA
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
Exception:

com.install4j.api.beans.UndefinedVariableException: installer:sys.windowsDir
	at com.install4j.runtime.installer.InstallerVariables.handleError(InstallerVariables.java:1295)
	at com.install4j.runtime.installer.InstallerVariables$InstallerReplacementCallback.getReplacement(InstallerVariables.java:1228)
	at com.install4j.runtime.util.StringUtil.replaceVariable(StringUtil.java:94)
	at com.install4j.runtime.util.StringUtil.replaceVariable(StringUtil.java:64)
	at com.install4j.runtime.installer.InstallerVariables.replaceVariables(InstallerVariables.java:425)
	at com.install4j.runtime.installer.InstallerVariables.replaceVariables(InstallerVariables.java:414)
	at com.install4j.runtime.installer.InstallerVariables.replaceVariables(InstallerVariables.java:410)
	at com.install4j.runtime.installer.InstallerVariables.replaceVariables(InstallerVariables.java:450)
	at com.install4j.api.beans.AbstractBean.replaceVariables(AbstractBean.java:91)
	at com.install4j.runtime.beans.actions.misc.RunExecutableAction.getExecutable(RunExecutableAction.java:62)
	at com.install4j.runtime.beans.actions.misc.RunExecutableAction.execute(RunExecutableAction.java:312)
	at com.install4j.runtime.beans.actions.SystemInstallOrUninstallAction.install(SystemInstallOrUninstallAction.java:29)
	at com.install4j.runtime.installer.ContextImpl$9.executeAction(ContextImpl.java:1759)
	at com.install4j.runtime.installer.ContextImpl$9.fetchValue(ContextImpl.java:1749)
	at com.install4j.runtime.installer.ContextImpl$9.fetchValue(ContextImpl.java:1746)
	at com.install4j.runtime.installer.helper.comm.actions.FetchObjectAction.execute(FetchObjectAction.java:14)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionWrapper(HelperCommunication.java:368)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.access$200(HelperCommunication.java:31)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication$1.run(HelperCommunication.java:97)

System properties:

gopherProxySet=false
awt.toolkit=sun.lwawt.macosx.LWCToolkit
java.specification.version=11
sun.cpu.isalist=
sun.jnu.encoding=UTF-8
java.class.path=/Applications/Akis Kart İzleme Aracı Kurulum programı.app/Contents/Resources/app/i4jruntime.jar
sun.awt.enableExtraMouseButtons=true
java.vm.vendor=Eclipse Adoptium
sun.arch.data.model=64
i4j.ownBundlePath=/Applications/Akis Kart İzleme Aracı Kurulum programı.app
install4j.exeDir=/Applications/
sun.font.fontmanager=sun.font.CFontManager
java.vendor.url=https://adoptium.net/
install4j.systemLanguage=en
user.timezone=Europe/Istanbul
os.name=Mac OS X
java.vm.specification.version=11
sun.java.launcher=SUN_STANDARD
user.country=TR
sun.boot.library.path=/private/var/folders/9g/vzl4c30x2fzdn290_t89hzg40000gn/T/4F214928-955B-4399-889A-F847E5DDAF98-60692-0004EE365D436BE9/jre.bundle/Contents/Home/lib
sun.java.command=com.install4j.runtime.launcher.MacLauncher
http.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
jdk.debug=release
sun.cpu.endian=little
user.home=/Users/ppp
user.language=en
java.specification.vendor=Oracle Corporation
java.version.date=2022-04-19
java.home=/private/var/folders/9g/vzl4c30x2fzdn290_t89hzg40000gn/T/4F214928-955B-4399-889A-F847E5DDAF98-60692-0004EE365D436BE5/jre.bundle/Contents/Home
file.separator=/
java.vm.compressedOopsMode=Zero based
line.separator=

java.specification.name=Java Platform API Specification
java.vm.specification.vendor=Oracle Corporation
java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
exe4j.moduleName=/Applications/Akis Kart İzleme Aracı Kurulum programı.app
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
ftp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
java.runtime.version=11.0.15+10
user.name=ppp
path.separator=:
os.version=14.2.1
java.runtime.name=OpenJDK Runtime Environment
file.encoding=UTF-8
java.vm.name=OpenJDK 64-Bit Server VM
java.vendor.version=Temurin-11.0.15+10
i4j.jreBundle=/var/folders/9g/vzl4c30x2fzdn290_t89hzg40000gj/T/4F214928-955B-4399-889A-F847E5DDAF98-60692-0004EE365D436BE9/jre.bundle
install4j.appDir=/Applications/Akis Kart İzleme Aracı Kurulum programı.app/Contents/Resources/
java.vendor.url.bug=https://github.com/adoptium/adoptium-support/issues
java.io.tmpdir=/var/folders/9g/vzl4c30x2fzdn290_t89hzg40000gn/T/
java.version=11.0.15
user.dir=/Applications/Akis Kart İzleme Aracı Kurulum programı.app/Contents/Resources/app
os.arch=x86_64
java.vm.specification.name=Java Virtual Machine Specification
java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
sun.os.patch.level=unknown
java.library.path=/Users/ppp/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.vm.info=mixed mode
java.vendor=Eclipse Adoptium
java.vm.version=11.0.15+10
i4j.tarFile=/Applications/Akis Kart İzleme Aracı Kurulum programı.app/Contents/Resources/app/jre.tar.gz
jdk.gtk.version=2
sun.io.unicode.encoding=UnicodeBig
java.class.version=55.0
socksNonProxyHosts=local|*.local|169.254/16|*.169.254/16
```

**Comment by karianna** [comment]
@taraniss This is an error in a native component provided by Akis kart izleme - you'll need to contact them for support on this.

**Comment by abdllhcrk** [comment]
did you solve this problem ? I have same problem while installing Akis kart izleme.
